### ISSUE TITLE
Performance Test

### ISSUE THREAD

**Issue by EricZs1995** [intel/QATzip#10]
Is there any introduction to the QATzip principle and performance test results?

**Comment by EricZs1995** [comment]
If so, please give me a link.

**Comment by daweiq** [comment]
Sorry, there are no such document.
QATzip is designed to accelerate the GZIP/DEFLATE processing with QAT acceleration.
It provides QAT API based on the QAT driver.
For more detailed of the QAT or QAT driver please refer to the following link:
https://01.org/zh/intel-quickassist-technology 

The QATzip performance is depending on the hardware platform. 
You can reach your Intel AE to get the performance report of your platform.
