### ISSUE TITLE
request: examples using qzCompressStream/qzDecompressStream

### ISSUE THREAD

**Issue by ralfonso** [intel/QATzip#11]
It would be helpful to have some examples using the stream API. `qzip` is limited to the buffer API and the test cases in `test/main.c` do not provide a real-world example since they attempt to allocate an input buffer equal to the size of the input file rather than setting a suitable buffer and making several calls to the qz function and setting `last` at the end.

I ask because I've run into a case where `qzDecompressStream` sets `strm->in_sz` to a negative number and the documentation is unclear about how to handle that case. Hopefully I can provide code soon, but the issue appears to be that `in_sz` is set to `copied_input + consumed` but `consumed` can include a value from `pending_in`, which should not be deducted from `in_sz`. This seems to occur in a case where `qzDecompressStream` goes through the loop once, processes some data and has some output, then goes through the loop again but `pending_in` is less than `buf_len` so it returns (with a debug msg to batch more data)

**Comment by ralfonso** [comment]
Here is some debug output from the case I described. 

```
Decompress Stream Start...
Copy to input from 0xc001700000, to 0x7fdb4ed01400, count 1043456
Before Call qzDecompress input_len 2092032 output_len 2092032 stream->pending_in 2092032 stream->pending_out 0 stream->in_sz 5120 stream->out_sz 21095061
qzDecompress data_fmt: 2
decompression src_len=2092032, hdr->extra.qz_e.src_sz = 3636930560, g_process.qz_init_status = 11, sess->hw_session_stat = 11, isStdGzipHeader = 1, switch to software.
Start qzSWDecompressMultiGzip: src_len 2092032 dest_len 2092032
decomp_sw data_fmt: 2

****** inflate init done with win_bits: 31 *****
Exit qzSWDecompress total_in: 362672 total_out: 2092032 avail_in: 1729360 avail_out: 0 msg: (null) src_len: 362672 dest_len: 2092032
Exit qzSWDecompressMultiGzip: src_len 362672 dest_len 2092032
Return code = 0
copy 2092032 to user output
Copy output 2092032 bytes
After Call qzDecompress input_len 362672 output_len 2092032 stream->pending_in 1729360 stream->pending_out 0 stream->in_sz 5120 stream->out_sz 19003029
Pending_out = 0, set pending_in 0
Copy to input from 0xc0017588b0, to 0x7fdb4ec01400, count 5120
Batch more input data...
Exit Decompress Stream input_len 362672 output_len 2092032 stream->pending_in 5120 stream->pending_out 0 stream->in_sz -680784 stream->out_sz 2092032
```

**Comment by daweiq** [comment]
There's a example of using streaming compression API in Nginx QATzip module for compression acceleration: 
https://github.com/intel/asynch_mode_nginx/blob/master/modules/nginx_qatzip_module/ngx_http_qatzip_filter_module.c 

In your case, the decompression is running on a QAT invalide platform and the input data is in GZIP format (without QZ extension), so it goes to the SW decompression, and the stream.in_sz is an unsigned int type while it is printed out as a int type. So, it's wired to see the in_sz show such a big value.

**Comment by ralfonso** [comment]
Ah, interesting! Yes, this case is part of a test to confirm compatibility with input created by an external source using zlib. 

I can add some more debug messages to determine why `in_sz` does not seem to be reflecting the actual amount of data consumed from the input.

**Comment by baergj** [comment]
I believe the issue here is incorrect input consumption accounting when `pending_in` is left non-zero after the termination of a previous call to `qzDecompressStream()`. When this occurs, the following code is incorrect:

`copyStreamInput()` does the following:
```c
strm->pending_in += cpy_cnt;
```

`qzDecompressStream()`:
```c
copied_input += copyStreamInput(strm, strm->in + consumed);
...
copied_input -= strm->pending_in;
```

Thus, in, `qzDecompressStream()`, `strm->pending_in >= copied_input`, making the above subtraction unsafe.

One way to fix this would be to eliminate the following line:
```c
copied_input -= strm->pending_in;
```
Add the following after incrementing `consumed`:
```c
copied_input -= input_len;
```
And then set `copied_input` to `0` whenever `pending_in` is set to `0`. It might be worth renaming `copied_input` to `input_bytes_in_pending` or something like that.

**Comment by baergj** [comment]
Actually, since this loop should never continue without first setting `pending_in = 0`, it's simpler to always assign `copied_input = copyStreamInput(strm, strm->in + consumed);`, instead of having to set `copied_input = 0;` later.

**Comment by baergj** [comment]
I see that this has been closed, but I didn't see any commits added to the repo. Is there a fix coming for this, or was it closed for some other reason?

**Comment by daweiq** [comment]
Yes, we are working on the fix for stream API.

The idea is only use copied_input accumulate all data copied into `stream_buf->in_buf` and return the copied_input as `stream_buf->in_sz` when the stream API return and avoid the `- stream_buf.pending_in`
and no needs to include consumed into `stream_buf->in_sz` when stream API return. 
While, we need change error handler for QZ_BUF_ERROR and will publish it in the next release.

**Comment by mythi** [comment]
>  When all cases passed, we will publish it in the next release.

Could you create a pull request so that we can review&test here too?

**Comment by daweiq** [comment]
Sorry, the patch cannot goes public before long review and test process which is close to a release process. 
While, I can share the way we fix it here for review and test.
