### ISSUE TITLE
support in-tree qat driver

### ISSUE THREAD

**Issue by bryanzhang-bytedance** [intel/QATzip#112]
Is it possible to update QATzip to build with [qatlib](https://github.com/intel/qatlib/)?

**Comment by daweiq** [comment]
QATzip should already support build based on QATLib. 
Any issue you see when buiding that way?

**Comment by GarenJian-Intel** [comment]
Please don't set ICP_ROOT when building qatzip with qatlib.

**Comment by bryanzhang-bytedance** [comment]
You're right. I think it works if you simply run `./configure` without trying to specify `ICP_ROOT`. Could the documentation please be updated to reflect this? Thanks.

**Comment by GarenJian-Intel** [comment]
Thanks for your reminder.
We will update the document.
