### ISSUE TITLE
add `Requires.private` section to `qatzip.pc` to support static builds

### ISSUE THREAD

**Issue by bryanzhang-bytedance** [intel/QATzip#114]
Right now, when I try to create a static build for a project that depends on QATzip, I run into various compilation errors. Adding the following line to the `qatzip.pc` pkgconfig file resolves the problem:

`Requires.private: libqat`

If this looks correct, could the generated pkgconfig file be changed accordingly so I don't have to make this change privately? Thank you.

**Comment by cfzhux** [comment]
Hi, due to QAT has two different versions of libraries libqat.so (generated by QATlib)and libqat_s.so (generated by QAT OOT),
We cannot determine which version of the qat library is being used, can't only include libqat in qatzip.pc.
