### ISSUE TITLE
CAP_SYS_ADMIN needed with 4.x kernels

### ISSUE THREAD

**Issue by mythi** [intel/QATzip#14]
qzip run by a non-root user needs ```CAP_SYS_ADMIN```.

The hugepage code in ```usdm_drv``` reads process' ```pagemap``` which added limitations with 4.x:

```
Since Linux 4.0 only users with the CAP_SYS_ADMIN capability can get PFNs.
In 4.0 and 4.1 opens by unprivileged fail with -EPERM.  Starting from
4.2 the PFN field is zeroed if the user does not have CAP_SYS_ADMIN.
```

**Comment by daweiq** [comment]
Thank you for point this out!
Yes, the current USDM pagemap solution have are not working properly for Linux 4.X.
The driver team is working on fix it.
Meanwhile, I will add this limitation to QATzip readme.
