### ISSUE TITLE
stopQAT: reset pcie_count

### ISSUE THREAD

**Issue by mythi** [intel/QATzip#15]
```g_process.pcie_count``` is not correctly de-initialized  in ```stopQAT```. Please consider the following patch:

```
diff --git a/src/qatzip.c b/src/qatzip.c
index 967ae03..c7b9f2c 100755
--- a/src/qatzip.c
+++ b/src/qatzip.c
@@ -346,6 +346,7 @@ static void stopQat(void)
     (void)icp_sal_userStop();
     g_process.num_instances = (Cpa16U)0;
     g_process.qz_init_status = QZ_NONE;
+    g_process.pcie_count = -1;
 }
```

The problem is that in "no HW" environment (pcie_count == 0), calling ```qzInit()``` again after a ```qzClose()```, the initialization is not completed correctly (```QZ_DUPLICATE``` is returned).

**Comment by daweiq** [comment]
Thank you for reporting this.
We will work on the fix.
