### ISSUE TITLE
initStream: hard coded memory allocation to PINNED_MEM

### ISSUE THREAD

**Issue by mythi** [intel/QATzip#16]
It's not possible to request ```COMMON_MEM``` when using the stream API. This is handy when experimenting in no HW/no usdm_drv environments.

**Comment by daweiq** [comment]
The stream API is designed to boost the performance in batch processing mode. It will accumulate little pieces data with the PINNED memory to avoid memory copy between QATzip and QAT driver and enable DMA between QAT and IA. 
So, it's less meaningful to use common memory in stream API.

**Comment by mythi** [comment]
> So, it's less meaningful to use common memory in stream API.

For early development/POCs, being able to use QATzip in SW-only mode and without QAT HW dependencies is handy.

**Comment by daweiq** [comment]
Good point!
Then, changing the memory flag for PINNED_MEM to COMMON_MEM should fix this.
