### ISSUE TITLE
initStream: insufficient output buffer for SW decompression

### ISSUE THREAD

**Issue by mythi** [intel/QATzip#17]
This looks faulty:

```
stream_buf->in_buf = qzMalloc(stream_buf->buf_len, NODE_0, PINNED_MEM);
stream_buf->out_buf = qzMalloc(stream_buf->buf_len, NODE_0, PINNED_MEM);
```

because ```stream_buf->buf_len = qz_sess->sess_params.strm_buff_sz```. Since the input buffer is read full (up to ```strm_buff_sz``` bytes), how to fit in the decompressed data in the output buffer that has the same size?

I'm getting ```invalid stored block lengths``` errors from zlib with this and they disappear when I make out_buf 10xbuf_len.

**Comment by daweiq** [comment]
The qzDecompressStream will decompress the 1st deflate block and copy the decompressed data to stream_buf->out_buf until it's full, then copy it to users out buffer specified by out* in qzDecompressStream; during the process if the users out* is full, it will return QZ_BUF_ERROR. 

While, we find error case for qzDecompressStream(), we are working on the fix now.

**Comment by mythi** [comment]
> While, we find error case for qzDecompressStream(), we are working on the fix now.

What's the error you're seeing?

**Comment by daweiq** [comment]
Error reported in https://github.com/intel/QATzip/issues/11
