### ISSUE TITLE
qzSWCompress fails to stream

### ISSUE THREAD

**Issue by mythi** [intel/QATzip#18]
I'm using the SW fallback via the streaming API. It looks qzSWCompress compresses full data blobs only and cannot be used with streaming data.

My use case that fails:
I'm compressing a big file in smaller data blobs, setting ```last = 1``` when the last blob is written. Then I'm de-compressing the compressed stream and comparing it to my original data. However, the reading stops already at the first smaller data blob I sent for compression.

**Comment by daweiq** [comment]
Yes, this is a bug in qzSWCompress API. Whenever it was called, the will always generate deflate block with BFINAL set. Should check the last argument before setting the flush flag for deflate call.
