### ISSUE TITLE
dataLenInBytes in destBuffers set to wrong size.

### ISSUE THREAD

**Issue by aakshintala** [intel/QATzip#19]
https://github.com/intel/QATzip/blob/6682d089d8cd951d67bcd2328cca007bd07c542b/src/qatzip.c#L1020

This seems to set the destBuffer pData size to the maximum expected size of the compressed input data, not the amount of memory that has actually been allocated for this buffer via qzMalloc on line 779.

You've probably not faced an issue from this because the HW probably doesn't really care about the value of this field. I'm trying to trap and forward QAT API calls and I kept getting a segfault when trying to copy destBuffer (my forwarding library was trying to memcpy dataInLenBytes from pData and was either copying garbage off the heap, or running into an unmapped page)...

**Comment by wkoux** [comment]
The length of the data we copy from the destBuffer is the data length actually generated by the driver, which will not exceed the length we assigned to the destBuffer, so the segment error will not occur.

In doCompressOut:
`if (dest_pinned && (0 == g_process.qz_inst[i].stream[j].seq)) {
                        g_process.qz_inst[i].dest_buffers[j]->pBuffers->pData =
                            g_process.qz_inst[i].stream[j].orig_dest;
                        g_process.qz_inst[i].stream[j].dest_pinned = 0;
                    } else {
                        QZ_MEMCPY(qz_sess->next_dest,
                                  g_process.qz_inst[i].dest_buffers[j]->pBuffers->pData,
                                  resl->produced,
                                  resl->produced);
                    }`
