### ISSUE TITLE
Single threaded execution results in a hung process

### ISSUE THREAD

**Issue by aakshintala** [intel/QATzip#20]
https://github.com/intel/QATzip/blob/6682d089d8cd951d67bcd2328cca007bd07c542b/src/qatzip.c#L1580

The way doCompressIn is currently written, it won't release control until the entire input has been offloaded to the QAT. doCompressOut must execute alongside in a separate thread, dequeuing completed requests to the QAT, in order for doCompressIn to finish... 
So the attempt to execute in a single thread on line 1580 results in a deadlock.

**Comment by daweiq** [comment]
Alternatively, to running in a single thread mode, you can play trade-off game by control the input data length you send to each qzCompress call. 
Saying the default chunk size is 64K and the default req_cnt_thrshold is 32, when  input size is less than 64K * 32 == 2MB, the API will work in single thread mode. 
```
    if (reqcnt > qz_sess->sess_params.req_cnt_thrshold) {
        pthread_create(&(qz_sess->c_th_i), NULL, doCompressIn, (void *)sess);
        doCompressOut((void *)sess);
        pthread_join(qz_sess->c_th_i, NULL);
    } else {
        doCompressIn((void *)sess);
        doCompressOut((void *)sess);
    }
```
