### ISSUE TITLE
Looking for qatzip.dll and Windows support

### ISSUE THREAD

**Issue by dmilkie** [intel/QATzip#21]
I'm using the Intel® QuickAssist Technology Software for **Windows** | W.1.1.0-29 that I found here: [https://01.org/intel-quickassist-technology](https://01.org/intel-quickassist-technology)

Specifically, I'm interested in using the QAT Zip portion.    In the release from the page I linked above, I downloaded [qatzip.lib](https://01.org/sites/default/files/downloads//qat1.7.w.1.1.0-0029.zip), but no .dll.  I was hoping to get my hands on a .dll.  Is this repo the place to compile a .dll, or whom should I contact that would be better to help me?

**Comment by shensongwu** [comment]
Hi,

Why do you must need a dll? Currently, we don't provide the dll and because it is not open source, so you can't compile it by yourself.

**Comment by dmilkie** [comment]
My software needs to load the qatzip library at run-time (ala Python, Matlab, etc...), which needs a .dll.  
As far as licensing, the .lib is under BSD LICENSE, and I wouldn't think that a .dll has any different functionality than the .lib except it's loaded at run-time instead of compile time.  

Do you know who I should contact about the Windows release?
