### ISSUE TITLE
make install problems

### ISSUE THREAD

**Issue by mythi** [intel/QATzip#24]
I've discovered the following installation gaps with v1.0.1:

1) `--prefix=/usr` fails

```
ln -s -f /usr/lib64/libqatzip.so /lib64
ln: '/usr/lib64/libqatzip.so' and '/lib64/libqatzip.so' are the same file
make: *** [Makefile:78: install] Error 1
```

2) `make install` does not handle SOVERSIONS correctly but only copies the `.so` file

**Comment by wkoux** [comment]
Hi Mikko

Thank you for your report.
Isuue 1 was introduced in v0.2.7.
Isuue 2 was introduced in v1.0.1.
We have fixed the two issues already in internal repo and will include the fixing patch in next release.
