### ISSUE TITLE
./configure does not work under Ubuntu

### ISSUE THREAD

**Issue by xwu2git** [intel/QATzip#25]
Please move #!/bin/bash to be the first line of the script.

**Comment by mythi** [comment]
See #13 . What's your error?

It works for me:
```
$ docker run -it -v $PWD:/QATzip ubuntu:19.10
root@982d925f0098:/# cd QATzip
root@982d925f0098:/QATzip# ./configure
Checking for zlib.h... Failed
QATzip need zlib.h to build
``´

**Comment by xwu2git** [comment]
Same as #13. Syntax error on line #54.

**Comment by xwu2git** [comment]
Failed if run under /bin/sh (docker build RUN uses /bin/sh)

**Comment by xwu2git** [comment]
/bin/sh configure
configure: 54: configure: Syntax error: "(" unexpected

If the first line is #!/bin/bash, the /bin/bash shell will be called to run the script. In your case, your first line is the license. Thus /bin/sh will be the shell.

**Comment by mythi** [comment]
I'm building QATzip with Docker and I have:

```
ARG QAT_ZIP_VERSION="v1.0.1"
RUN git clone https://github.com/intel/QATzip
RUN cd /QATzip && git checkout $QAT_ZIP_VERSION && \
    ./configure --with-ICP_ROOT=/ && make all install
```

**Comment by xwu2git** [comment]
https://github.com/xwu2git/Dockerfiles/blob/qat/QAT/ubuntu-18.04/media/nginx/Dockerfile

Line 56. I have to add /bin/bash before configure to make it work, or the line will fail with syntax error.

**Comment by mythi** [comment]
Some shells seems to get it right from where it is now. Moving the shebang to be the very first line makes sense.

@xwu2git btw, you don't necessarily have to download and build openssl yourself (the latest QAT_Engine is able to use the distros libraries and headers).

**Comment by xwu2git** [comment]
Yes, I notice that. However, we need to support different OS distributions from centos 7.4-7.6 and ubuntu 16.04-18.04 and future versions. QAT_Engine requires different config flags for different openssl versions. It is difficult to control the behavior (if the OS distribution upgrades.) Compiling a known-working version is at least manageable. 

BTW, unrelated, does QATzip and/or QATengine require to use/mount hugepages? My experiment shows they do. However, looking at the intel device plugins repo, they seem to go by without using hugepages.

**Comment by daweiq** [comment]
@xwu2git  Yes, you are right, QAT driver can use the pinned continuous memory to save the memory copy from user-space to kernel. It's recommended to have huge-page enabled.

**Comment by daweiq** [comment]
@xwu2git  It's strange to see the "/bin/sh" does not support shebang to invoke specified interpreter for configure file. Even in that case, I think keeping the 1st line of "#! /bin/bash" would help user to understand which SHELL to use, so they can call it manually afterwards.  

Any thought on it, please let me know!

**Comment by mythi** [comment]
> However, looking at the intel device plugins repo, they seem to go by without using hugepages.

It's the property of the `usdm_drv` and the applications don't deal with hugepages from kubernetes resources.

**Comment by xwu2git** [comment]
@mythi: However, the /dev/hugepages folder must be mounted, or QATzip will not work. I don't know why Kubernetes would magically work (although I haven't tested it my self.)

@daweiq, My understanding is that shebang only works if it is the first line of the script, followed by an empty line. The configure script instead has license lines before shebang.

**Comment by mythi** [comment]
@xwu2git 

> @mythi: However, the /dev/hugepages folder must be mounted, or QATzip will not work.

Looks like you're right. We haven't used/tested QATzip with kubernetes and that's why hugepages are not mentioned with device plugins. For QATzip based apps in kubernetes, the right approach is to request `hugepages-2Mi` resources for the pod instead of mounting /dev/hugepages.

**Comment by daweiq** [comment]
@xwu2git I tried to move the shebang to the very 1st line, while same error  happened.

```
root@qat-weiweiqi-upf:.../isg_cid-qatzip# git diff --color
diff --git a/configure b/configure
index edd0051..a6dfabc 100755
--- a/configure
+++ b/configure
@@ -1,3 +1,5 @@
+#! /bin/bash
+
################################################################
 #   BSD LICENSE
 #
@@ -31,7 +33,7 @@
 #   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 ################################################################
-#! /bin/bash
+
 set -o errexit

 prefix=/usr/local
root@qat-weiweiqi-upf:/home/weiweiqi/QATzip/isg_cid-qatzip# sh ./configure
./configure: 51: ./configure: Syntax error: "(" unexpected
```

**Comment by daweiq** [comment]
@mythi @xwu2git if the hugepage has not been configured the USDM module inside the QAT drive will map pinned memory from kernel for QATzip.

**Comment by xwu2git** [comment]
@deweiq Strange. Maybe the issue is in your function definition:

Usually, a function can be defined as:
(1) function function_name {} or
(2) function_name() { } 
I could not find any reference that a function is defined as function function_name() {}.
Could you try removing () in line 54?

**Comment by xwu2git** [comment]
https://stackoverflow.com/questions/6212219/passing-parameters-to-a-bash-function

**Comment by daweiq** [comment]
@xwu2git  Even after removing the '{}', I still got "function" not found" error.
Seems, it still using dash instead of the bash to interpret the configure.
The shebang does not work in either cases. 

```
root@qat-weiweiqi-upf:~/isg_cid-qatzip# git diff --color
diff --git a/configure b/configure
index edd0051..8c4f3da 100755
--- a/configure
+++ b/configure
@@ -1,3 +1,5 @@
+#! /bin/bash
+
 ################################################################
 #   BSD LICENSE
 #
@@ -31,7 +33,7 @@
 #   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 ################################################################
-#! /bin/bash
+
 set -o errexit

 prefix=/usr/local
@@ -46,8 +48,7 @@ LN_S='ln -s'
 RM='rm -f'
 INSTALL='install'

-function exit_conf()
-{
+function exit_conf {
   rm -f qztest* qzlib*
   rm -f a.out
   exit
(reverse-i-search)`g': ^Ct diff --color
root@qat-weiweiqi-upf:/home/weiweiqi/QATzip/isg_cid-qatzip# sh ./configure
./configure: 51: ./configure: function: not found
```

**Comment by mythi** [comment]
Drop the whitespace?

`+#! /bin/bash`

**Comment by daweiq** [comment]
The same 
```
root@qat-weiweiqi-upf:~/isg_cid-qatzip# git diff --color
diff --git a/configure b/configure
index edd0051..b0bc881 100755
--- a/configure
+++ b/configure
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 ################################################################
 #   BSD LICENSE
 #
@@ -31,7 +33,7 @@
 #   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 ################################################################
-#! /bin/bash
+
 set -o errexit

 prefix=/usr/local
@@ -46,8 +48,7 @@ LN_S='ln -s'
 RM='rm -f'
 INSTALL='install'

-function exit_conf()
-{
+function exit_conf {
   rm -f qztest* qzlib*
   rm -f a.out
   exit
root@qat-weiweiqi-upf:~/isg_cid-qatzip# dash ./configure
./configure: 51: ./configure: function: not found
```
