### ISSUE TITLE
Does QAT communication chipest 8950 support stateful Deflate Compression?

### ISSUE THREAD

**Issue by perfectxhj** [intel/QATzip#26]
Hi,
Now I am trying to run the stateful data compression sample located in /dc/stateful_sample .My QAT is COMMUNICATION CHIPSET 8950. However,I found that this function is not supported by QAT. When i want to run this sample,the debug output is as following:

[root@node5 stateful_sample]# ./dc_stateful_sample
main(): Starting Stateful Compression Sample Code App ...
dcStatefulSample(): cpaDcQueryCapabilities
dcStatefulSample(): Error: Unsupported functionality compression
main():
Stateful Compression Sample Code App failed

Then i found the definition of the compression capabilities in sal_compression.c :

#ifdef CNV_STRICT_MODE
pInstanceCapabilities->statefulDeflateCompression = CPA_FALSE;
#else
pInstanceCapabilities->statefulDeflateCompression = CPA_TRUE;

I did not find the definition of CNV_STRICT_MODE，so is my QAT really not support stateful deflate compression?

Regards.

**Comment by daweiq** [comment]
Yes, for compression QAT driver support stateless mode only. 
And for decompression it support both  stateful and stateless mode. 
For more information you can refer to 
https://01.org/intel-quickassist-technology
