### ISSUE TITLE
Inaccurate calculation of throughput in performance test

### ISSUE THREAD

**Issue by jimmyou587** [intel/QATzip#32]
I noticed the way of calculating the compression/decompression throughput in run_performance_test.sh is to just adding up the throughput number of all the threads in result_comp/result_decomp.
```echo > result_comp<br/>
for((numProc_comp = 0; numProc_comp < $process; numProc_comp ++))
do
    $QZ_ROOT/test/test -m 4 -l 1000 -t $thread -D comp $extra_args >> result_comp 2>&1  &
done
wait
compthroughput=`awk '{sum+=$8} END{print sum}' result_comp`
echo "compthroughput=$compthroughput Gbps"

echo > result_decomp
for((numProc_decomp = 0; numProc_decomp < $process; numProc_decomp ++))
do
    $QZ_ROOT/test/test -m 4 -l 1000 -t $thread -D decomp $extra_args >> result_decomp 2>&1  &
done
wait
decompthroughput=`awk '{sum+=$8} END{print sum}' result_decomp`
echo "decompthroughput=$decompthroughput Gbps"
```

It seems to have the assumption that all threads start and finish at the same time, which is apparently not true in most cases. 

For example, below is the output of result_comp after running the performance test script
`[INFO] srv=COMP, tid=1, verify=0, count=1000, msec=8782055, bytes=1029744, 0.873621 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=0, verify=0, count=1000, msec=8895848, bytes=1029744, 0.862446 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=3, verify=0, count=1000, msec=9924964, bytes=1029744, 0.773019 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=2, verify=0, count=1000, msec=9935799, bytes=1029744, 0.772177 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=0, verify=0, count=1000, msec=8787976, bytes=1029744, 0.873033 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=1, verify=0, count=1000, msec=8872350, bytes=1029744, 0.864730 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=2, verify=0, count=1000, msec=9932433, bytes=1029744, 0.772438 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=3, verify=0, count=1000, msec=9947483, bytes=1029744, 0.771270 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=0, verify=0, count=1000, msec=8867084, bytes=1029744, 0.865244 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=2, verify=0, count=1000, msec=8892059, bytes=1029744, 0.862814 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=1, verify=0, count=1000, msec=9919737, bytes=1029744, 0.773427 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=3, verify=0, count=1000, msec=9930240, bytes=1029744, 0.772609 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=0, verify=0, count=1000, msec=8843361, bytes=1029744, 0.867565 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=2, verify=0, count=1000, msec=8902020, bytes=1029744, 0.861848 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=1, verify=0, count=1000, msec=9906058, bytes=1029744, 0.774495 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=3, verify=0, count=1000, msec=9932502, bytes=1029744, 0.772433 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=3, verify=0, count=1000, msec=7337955, bytes=1029744, 1.045549 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=2, verify=0, count=1000, msec=7390413, bytes=1029744, 1.038127 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=0, verify=0, count=1000, msec=10132327, bytes=1029744, 0.757199 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=1, verify=0, count=1000, msec=10137029, bytes=1029744, 0.756848 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=2, verify=0, count=1000, msec=7311454, bytes=1029744, 1.049339 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=3, verify=0, count=1000, msec=7355766, bytes=1029744, 1.043017 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=1, verify=0, count=1000, msec=10117367, bytes=1029744, 0.758319 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=0, verify=0, count=1000, msec=10140230, bytes=1029744, 0.756609 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=0, verify=0, count=1000, msec=7371144, bytes=1029744, 1.040841 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=1, verify=0, count=1000, msec=7394235, bytes=1029744, 1.037591 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=3, verify=0, count=1000, msec=10113654, bytes=1029744, 0.758597 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=2, verify=0, count=1000, msec=10136290, bytes=1029744, 0.756903 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=2, verify=0, count=1000, msec=7283644, bytes=1029744, 1.053345 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=3, verify=0, count=1000, msec=7319118, bytes=1029744, 1.048240 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=0, verify=0, count=1000, msec=10126481, bytes=1029744, 0.757636 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%
[INFO] srv=COMP, tid=1, verify=0, count=1000, msec=10134585, bytes=1029744, 0.757031 Gbps, input_len=1029744, comp_len=211675, ratio=20.556080%`

The compression throughput being printed in the terminal is
`compthroughput=27.5284 Gbps`

Should it be more accurate to always do it as follows?

Throughput = Total Processed Data of All Threads / (End Time of Last Thread - Start Time of First Thread)

**Comment by feixuex** [comment]
Hi jimmyou587,

All the threads are started at the same time. They are synchronized by the conditional variable `g_start_condition`.  
In thread, it waits on this variable to start compress/decompress, while the main thread will broadcast this condition to let the other threads to start at the same time. 

```
/* --- test/main.c --- */
1144     while (!g_ready_to_start) {
1145         rc = pthread_cond_wait(&g_start_cond, &g_cond_mutex);
1146         if (rc != 0) {
1147             QZ_ERROR("Failure to pthread_cond_wait, status = %d\n", rc);
1148             goto done;
1149         }
1150     }
```


```
/* --- test/main.c --- */
4025         g_ready_to_start = 1;
4026         ret = pthread_cond_broadcast(&g_start_cond);
4027         if (ret != 0) {
4028             QZ_ERROR("Failure calling pthread_cond_broadcast, status = %d\n", ret);
4029             goto done;
4030         }
```

**Comment by jimmyou587** [comment]
Hi feixuex,

Thanks for the quick response and the explanation. I think I missed this part in the test code. In this case, given all the threads starting at the same time, can we assume they can all run in parallel? My understanding is each endpoint can support upto 128 rings by changing the parameters in the configuration files and each thread is corresponding to one ring. Can we assume the compression/decompression traffic being sent to different rings is completely independent with each other?

**Comment by feixuex** [comment]
` can we assume they can all run in parallel? `
Yes. 
` Can we assume the compression/decompression traffic being sent to different rings is completely independent with each other? `
Yes. 
` My understanding is each endpoint can support upto 128 rings by changing the parameters in the configuration files and each thread is corresponding to one ring. `
We cannot say like this. The endpoint is not aware of the existence of the rings. In order to use QAT,  the only thing we do is to get/apply instances.

**Comment by jimmyou587** [comment]
Thanks for the explanation. One last question I have is, what is the benefit of being able to config both num_process and num_instance in the config files?

**Comment by feixuex** [comment]
the num_process and num_instance has the equation:
```num_process * instances_per_process * num_instance_per_process <= total rings```

So this  will make you allocate as many instances as you can to make use of the hardware. Which will raise the concurrency and take advantages of the QAT devices. 

An example: if you run 100 processes and every process needs 1 instances, you can set them as follows:
```
num_process = 100
num_instance = 1
```
Thus each process can get instances from devices.

**Comment by jimmyou587** [comment]
What if the user wants to run 1 process with 32 threads? In this case, all traffic will go to one endpoint right?

Why not only have num_instance in the configuration file so users can run as many processes or threads based on the number of instances?

**Comment by feixuex** [comment]
No, thread is LWP(light weight process), the situation of multi threads is the same with processes. So in your case, each thread will get some instances.
The second question is because there can be more than 1 sections to set the user process instance. So giving a max process for one section, I think it's a wise decision.
You can reference [this document](https://01.org/sites/default/files/downloads//336210-012-intel-qat-swpg.pdf).

**Comment by jimmyou587** [comment]
Thanks for the clarifications. I am closing this ticket now.
