### ISSUE TITLE
QATzip support static link zlib-1.2.11 library?

### ISSUE THREAD

**Issue by lizj3624** [intel/QATzip#33]
./sbin/nginx -V
nginx version: nginx/1.16.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
configure arguments: --prefix=/export/servers/asynch_mode_nginx --with-http_ssl_module --with-http_stub_status_module --with-http_v2_module --with-stream --with-stream_ssl_module --with-pcre=/export/servers/myqat/pcre-8.40 --with-pcre-jit --with-zlib=/export/servers/myqat/zlib-1.2.11 --with-pcre-opt='-g -Ofast -fPIC -m64 -march=native -fstack-protector-strong -D_FORTIFY_SOURCE=2' --with-zlib-opt='-g -Ofast -fPIC -m64 -march=native -fstack-protector-strong -D_FORTIFY_SOURCE=2' --add-dynamic-module=modules/nginx_qatzip_module --add-dynamic-module=modules/nginx_qat_module --with-cc-opt=' -fPIC -DNGX_SECURE_MEM -I/export/servers/Openssl-1.1.1g/include -I/export/servers/myqat/qat/QAT-1.7/QATzip/include -Wno-error=deprecated-declarations' --with-ld-opt='-Wl,-rpath=/export/servers/Openssl-1.1.1g/lib -L/export/servers/Openssl-1.1.1g/lib -L/export/servers/myqat/qat/QAT-1.7/QATzip/src -lqatzip -L/export/servers/myqat/zlib-1.2.11 -lz -lssl'

 ldd ./sbin/nginx
	linux-vdso.so.1 =>  (0x00007ffddecf2000)
	libqatzip.so.1 => /export/servers/qat/QATzip/lib64/libqatzip.so.1 (0x00007ff951723000)
	libssl.so.1.1 => /export/servers/Openssl-1.1.1g/lib/libssl.so.1.1 (0x00007ff95148c000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff951288000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff95106c000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007ff950e35000)
	libcrypto.so.1.1 => /export/servers/Openssl-1.1.1g/lib/libcrypto.so.1.1 (0x00007ff950978000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff9505ab000)
	libqat_s.so => /export/servers/myqat/qat/qat-1.7-driver/lib/libqat_s.so (0x00007ff9502d6000)
	libusdm_drv_s.so => /export/servers/myqat/qat/qat-1.7-driver/lib/libusdm_drv_s.so (0x00007ff9500be000)
	libz.so.1 => /lib64/libz.so.1 (0x00007ff94fea8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff951cbb000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007ff94fca5000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007ff94fa8f000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff94f887000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007ff94f682000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff94f380000)
	libdw.so.1 => /lib64/libdw.so.1 (0x00007ff94f131000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff94ef1b000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007ff94ed16000)
	libelf.so.1 => /lib64/libelf.so.1 (0x00007ff94eafe000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007ff94e8d8000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007ff94e6c8000)

I found nginx link /lib64/libz.so.1，not /export/servers/myqat/zlib-1.2.11，QATzip not support static link zlib-1.2.11 library？

**Comment by feixuex** [comment]
Hi Eric,
    QATzip does not support static link to zlib. Currently only dynamic link is supported. Would you please give more detail about your needs or requirements?

**Comment by lizj3624** [comment]
I want QATzip dynamic link my own installed zlib (/export/servers/myqat/zlib-1.2.11)，not /lib64/libz.so.1

**Comment by feixuex** [comment]
try this option: 
`--with-ld-opt='-Wl,-rpath=/export/servers/Openssl-1.1.1g/lib,-rpath=/export/servers/myqat/zlib-1.2.11 -L/export/servers/Openssl-1.1.1g/lib -L/export/servers/myqat/qat/QAT-1.7/QATzip/src -lqatzip -lz -lssl'`

**Comment by lizj3624** [comment]
ok，thanks
