### ISSUE TITLE
Not improve performance when used qatzip

### ISSUE THREAD

**Issue by lizj3624** [intel/QATzip#34]
### **1、version**
Deiver： qat1.7.l.4.9.0-00008
Qat_Engine：v0.5.44
OpenSSL-1.1.1g
QATzip：v1.0.1

### **2、./nginx/sbin/nginx -V**
nginx version: openresty/1.15.8.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
built with OpenSSL 1.1.1g 21 Apr 2020
TLS SNI support enabled
configure arguments: --prefix=/export/servers/OpenResty-1.15.8/nginx --with-cc-opt='-O2 -ggdb -O2 -I/export/servers/OpenResty-1.15.8/include -I/export/servers/OpenSSL-1.1.1g/include -I/export/servers/qat/QATzip/include -I/export/servers/zlib-1.2.11/include -D NGX_SECURE_MEM -D JD_NGX_SSL_HANDSHAKE_TIME -D JD_NGX_HTTP_UPSTREAM_RANDOM -Wno-error=deprecated-declarations' --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.15 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.7 --with-ld-opt='-Wl,-rpath,/export/servers/OpenResty-1.15.8/luajit/lib -Wl,-rpath=/export/servers/OpenSSL-1.1.1g/lib -L/export/servers/OpenSSL-1.1.1g/lib -L/export/servers/qat/QATzip/lib64 -lqatzip -L/export/servers/zlib-1.2.11/lib -lz -lssl' --with-pcre=/root/rpmbuild/BUILD/OpenResty-1.15.8-2.3-56.851dbdb/thirdparty/pcre-8.39 --with-pcre-jit --with-threads --with-http_auth_request_module --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_slice_module --add-module=/root/rpmbuild/BUILD/OpenResty-1.15.8-2.3-56.851dbdb/thirdparty/lua-ssl-nginx-module --add-module=/root/rpmbuild/BUILD/OpenResty-1.15.8-2.3-56.851dbdb/thirdparty/ngx_http_dyups_module --add-module=/root/rpmbuild/BUILD/OpenResty-1.15.8-2.3-56.851dbdb/thirdparty/ngx_http_sticky_module --with-stream --with-stream_ssl_module --with-openssl-async --with-http_gunzip_module --with-pcre-opt='-g -Ofast -fPIC -m64 -march=native -fstack-protector-strong -D_FORTIFY_SOURCE=2' --add-dynamic-module=/root/rpmbuild/BUILD/OpenResty-1.15.8-2.3-56.851dbdb/thirdparty/nginx_qat_module --add-dynamic-module=/root/rpmbuild/BUILD/OpenResty-1.15.8-2.3-56.851dbdb/thirdparty/nginx_qatzip_module --with-stream --with-stream_ssl_preread_module

### **3、ldd nginx/sbin/nginx**
linux-vdso.so.1 =>  (0x00007fff5dadb000)
libqatzip.so.1 => /export/servers/qat/QATzip/lib64/libqatzip.so.1 (0x00007f62f51d1000)
libz.so.1 => /export/servers/zlib-1.2.11/lib/libz.so.1 (0x00007f62f4fb6000)
libssl.so.1.1 => /export/servers/OpenSSL-1.1.1g/lib/libssl.so.1.1 (0x00007f62f4d1f000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f62f4b1b000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f62f48ff000)
libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f62f46c8000)
libluajit-5.1.so.2 => /export/servers/OpenResty-1.15.8/luajit/lib/libluajit-5.1.so.2 (0x00007f62f4449000)
libm.so.6 => /lib64/libm.so.6 (0x00007f62f4147000)
libcrypto.so.1.1 => /export/servers/OpenSSL-1.1.1g/lib/libcrypto.so.1.1 (0x00007f62f3c8a000)
libc.so.6 => /lib64/libc.so.6 (0x00007f62f38bd000)
libqat_s.so => /export/servers/qat/QAT_Driver/lib/libqat_s.so (0x00007f62f35e8000)
libusdm_drv_s.so => /export/servers/qat/QAT_Driver/lib/libusdm_drv_s.so (0x00007f62f33d0000)
/lib64/ld-linux-x86-64.so.2 (0x00007f62f583c000)
libfreebl3.so => /lib64/libfreebl3.so (0x00007f62f31cd000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f62f2fb7000)
libudev.so.1 => /lib64/libudev.so.1 (0x00007f62f2da1000)
librt.so.1 => /lib64/librt.so.1 (0x00007f62f2b99000)
libcap.so.2 => /lib64/libcap.so.2 (0x00007f62f2994000)
libdw.so.1 => /lib64/libdw.so.1 (0x00007f62f2745000)
libattr.so.1 => /lib64/libattr.so.1 (0x00007f62f2540000)
libelf.so.1 => /lib64/libelf.so.1 (0x00007f62f2328000)
liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f62f2102000)
libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f62f1ef2000)

### **5、cat nginx.conf**
```conf
      load_module modules/ngx_ssl_engine_qat_module.so;
      load_module modules/ngx_http_qatzip_filter_module.so;

      events {
             use epoll;
             multi_accept on;
             worker_connections  102400;
      }

      ssl_engine {
             use_engine qat;
             default_algorithms ALL;
             qat_engine {
                      qat_offload_mode async;
                      qat_notify_mode poll;
                      qat_poll_mode heuristic;
                      qat_sw_fallback on;
             }
      }
http {
       gzip  on;
       gzip_http_version   1.0;
       gzip_proxied any;
    qatzip_sw failover;
    qatzip_min_length 128;
    qatzip_comp_level 1;
    qatzip_buffers 16 8k;
    qatzip_types text/css text/javascript text/xml text/plain text/x-component application/javascript application/json application/xml application/rss+xml font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml application/octet-stream image/jpeg;
    qatzip_chunk_size   64k;
    qatzip_stream_size  256k;
    qatzip_sw_threshold 256;
}
```
### **6、top and perf top**

<img width="1038" alt="top-cpu-qat-zip" src="https://user-images.githubusercontent.com/1217777/85492851-6e9d0800-b608-11ea-9647-62f545fd2eb9.png">
<img width="1057" alt="WX20200624-103151@2x" src="https://user-images.githubusercontent.com/1217777/85492873-78267000-b608-11ea-9df6-a2e0f2bdb6a4.png">

I think not improve performance when used qatzip

**Comment by feixuex** [comment]
Could you please provide the access.log and error.log ?

**Comment by lizj3624** [comment]
cat error.log
2020/06/29 11:10:01 [alert] 32449#32449: QAT Engine failed: HEARTBEAT_POLL
2020/06/29 11:10:01 [alert] 32465#32465: QAT Engine failed: HEARTBEAT_POLL
2020/06/29 11:10:01 [alert] 32458#32458: QAT Engine failed: HEARTBEAT_POLL
2020/06/29 11:10:01 [alert] 32461#32461: QAT Engine failed: HEARTBEAT_POLL
2020/06/29 11:10:01 [alert] 32456#32456: QAT Engine failed: HEARTBEAT_POLL
2020/06/29 11:11:21 [alert] 32463#32463: QAT Engine failed: HEARTBEAT_POLL
Error userStarMultiProcess(-1), switch to SW if permitted
g_process.qz_init_status = QZ_NO_HW
Error userStarMultiProcess(-1), switch to SW if permitted
g_process.qz_init_status = QZ_NO_HW
Error userStarMultiProcess(-1), switch to SW if permitted
g_process.qz_init_status = QZ_NO_HW
Error userStarMultiProcess(-1), switch to SW if permitted
g_process.qz_init_status = QZ_NO_HW

[error.log](https://github.com/intel/QATzip/files/4843597/error.log)

**Comment by zhangp8x** [comment]
Instance is not enough in your env, please provide your nginx.conf and your driver configuration files(no cut off). And please walk through: https://github.com/intel/asynch_mode_nginx#intel-quickassist-technology-qat-async-mode-nginx

**Comment by lizj3624** [comment]
[nginx.conf.tar.gz](https://github.com/intel/QATzip/files/4843699/nginx.conf.tar.gz)
[qat.conf.tar.gz](https://github.com/intel/QATzip/files/4843701/qat.conf.tar.gz)

**Comment by zhangp8x** [comment]
This comments is used to solve your error in your errorlog:

- Please check https://github.com/intel/asynch_mode_nginx#limitations, you have set worker number to auto` worker_processes    auto;`, means the number of your nginx workers is the same as your cpu numbers. 
- DH895XX has a limitation that can only support up to 32 dc with 32 cy, make sure your workers are less than or equal to 32. 

You can check the following link to see if it can solve your problem: https://github.com/intel/asynch_mode_nginx/issues/34#issuecomment-602501312.

**Comment by lizj3624** [comment]
1、I modify worker_processes 16
2、I tested gzip and without gzip
     **1）gzip detailed results:**
    ./bin/wrk -c3000 -t200 -d30s  -H 'Accept-Encoding: gzip' https://my-qat.jd.com:4443/ 
    Running 30s test @ https://my-qat.jd.com:4443/
  200 threads and 3000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   396.82ms  175.91ms   2.00s    78.68%
    Req/Sec    38.62     24.69   630.00     83.33%
    230376 requests in 30.10s, 14.99GB read
    Socket errors: connect 6, read 0, write 0, timeout 376
    **Requests/sec:   7653.29**
    **Transfer/sec:    509.99MB**
![企业咚咚20200630172033](https://user-images.githubusercontent.com/1217777/86110764-8d176d80-baf8-11ea-9585-328ed6ac06b6.jpg)
![企业咚咚20200630172141](https://user-images.githubusercontent.com/1217777/86110799-956fa880-baf8-11ea-9dc7-0cfbbf5d4de3.jpg)

  **2）without gzip detailed results:**
      ./bin/wrk -c3000 -t200 -d30s https://my-qat.jd.com:4443/  
      Running 30s test @ https://my-qat.jd.com:4443/
      200 threads and 3000 connections
      Thread Stats   Avg      Stdev     Max   +/- Stdev
      Latency    97.91ms  250.05ms   2.00s    91.19%
      Req/Sec   349.87    447.50     4.22k    82.68%
      2122708 requests in 30.10s, 21.91GB read
      Socket errors: connect 0, read 0, write 0, timeout 10332
      Non-2xx or 3xx responses: 1969401
      **Requests/sec:  70518.56**
      **Transfer/sec:    745.32MB**
![企业咚咚20200630171949](https://user-images.githubusercontent.com/1217777/86111367-3cecdb00-baf9-11ea-87a4-768cd2c78285.jpg)

**Requests/sec of without gzip: 70518.56， Requests/sec of gzip: 7653.29，close to 10 times**

**Comment by zhangp8x** [comment]
Yes, you got the correct result, the result you provided in not related to QAT.
By using QAT:
- we should compare gzip(software) and QATzip by the same test command: ./bin/wrk -c3000 -t200 -d30s -H 'Accept-Encoding: gzip' https://my-qat.jd.com:4443/
By using QATzip we can cut the cpu usage in server, while do gzip compress.

**Comment by zhangp8x** [comment]
Any more questions? This issue would be closed in 7 days, please reopen this issue if you still have questions then.

**Comment by lizj3624** [comment]
Can QATzip's performance be improved?

**Comment by zhangp8x** [comment]
Could you please provide your performance data for 1 worker? The performance of QAT should be done in single worker first.

**Comment by zhangp8x** [comment]
And please use asynch_mode_nginx, try https://github.com/intel/asynch_mode_nginx/tree/master/test/performance_bkm

**Comment by lizj3624** [comment]
1、I test gzip of QATzip asynch_mode_nginx，I think performance of QAT HTTPS is ok。
2、worker_processes 16
```shell
      ./bin/wrk -c3000 -t200 -d30s -H 'Accept-Encoding: gzip' https://my-qat.jd.com:4443/
      Running 30s test @ https://my-qat.jd.com:4443/
      200 threads and 3000 connections
      Thread Stats Avg Stdev Max +/- Stdev
      Latency 396.82ms 175.91ms 2.00s 78.68%
      Req/Sec 38.62 24.69 630.00 83.33%
      230376 requests in 30.10s, 14.99GB read
      Socket errors: connect 6, read 0, write 0, timeout 376
      Requests/sec: 7653.29
      Transfer/sec: 509.99MB
```

**Comment by zhangp8x** [comment]
Below is my wrk performance data:
```
# wrk -c1500 -t200 -d30s -H 'Accept-Encoding: gzip' https://192.168.2.1:443/
Running 30s test @ https://192.168.2.1:443/
  200 threads and 1500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.71ms    2.66ms  24.06ms   68.40%
    Req/Sec    15.73     10.51    90.00     70.05%
  59878 requests in 30.10s, 36.60MB read
Requests/sec:   1989.27
Transfer/sec:      1.22MB
# wrk -c1500 -t200 -d30s https://192.168.2.1:443/
Running 30s test @ https://192.168.2.1:443/
  200 threads and 1500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.20ms    1.28ms  28.73ms   89.39%
    Req/Sec    31.12     20.37   212.00     66.30%
  147857 requests in 30.10s, 119.15MB read
Requests/sec:   4912.19
Transfer/sec:      3.96MB
```
When request a gzip header, after handshake nginx worker would wait for QATzip to finish its compress phrase, so the Requests/sec is much more lower than non gzip header one. In my env, the cpu usage is 10% less usage in QATzip mode than  that of non gzip header in comparison.

**Comment by zhangp8x** [comment]
Any more questions? This issue would be closed in 7 days, please reopen this issue if you still have questions then.
