### ISSUE TITLE
Are Xeon D QAT boards supported?

### ISSUE THREAD

**Issue by JoeUX** [intel/QATzip#35]
The hardware section here only mentions the QAT adapters. However, QuickAssist is also available on several Xeon D boards. Does this library support QAT on Xeon D as well?

You can see the Skylake Xeon D boards with QAT [here](https://en.wikichip.org/wiki/intel/xeon_d#D-2100_Series_.28Skylake.29).

**Comment by zhangp8x** [comment]
Yes, Xeon-D 2100 supports QAT, detailed product brief available here: https://www.intel.cn/content/dam/www/public/us/en/documents/product-briefs/xeon-d-2100-product-brief.pdf
