### ISSUE TITLE
Replace zlib or snappy

### ISSUE THREAD

**Issue by seven7777777** [intel/QATzip#38]
Is there any way of replacing zlib/snappy just by only recompile and link my app code, and not to change any of my code? Just want to take a simple test.

**Comment by feixuex** [comment]
What do you mean by "replacing zlib"? upgrade?

**Comment by seven7777777** [comment]
Thx.
i mean by just changing gcc  link options: -lz to -lqatzip.
 if not, what is the simplest way to move from zlib/snappy to qatzip in my app code?

**Comment by feixuex** [comment]
But zlib is a dependency of qatzip.
If you have an installed qatzip, just link your app with -lqatzip.

**Comment by seven7777777** [comment]
Ok. Do i  need to make any change to my app code?

**Comment by seven7777777** [comment]
im using rocksdb with zlib.  do i need to make change to rocksdb code?

**Comment by feixuex** [comment]
I think it depends on what zlib API you use in rocksdb. Because qatzip is not a replacement of zlib. By using qatzip, it just accelerates the de/compression. You can reference the [API](https://github.com/intel/QATzip/blob/master/include/qatzip.h).

**Comment by seven7777777** [comment]
Just link my app with -lqatzip.  How do I know qatzip zlib accelerating  is working? any log or perf tool?

**Comment by seven7777777** [comment]
Just link my app with -lqatzip. How do I know qatzip is working? any log  or perf tool?

**Comment by feixuex** [comment]
You can watch `/sys/kernel/debug/qat_c6xx_0000:XX:XX:XX.X/fw_counters` to know whether QAT works. Replace the XXX with corrected address in your OS.

**Comment by seven7777777** [comment]
just no update in /sys/kernel/debug/qat_c6xx_0000:XX:XX:XX.X/fw_counters , guess qat is not working, and I do have linked with qatzip:
        linux-vdso.so.1 =>  (0x00007ffe2e145000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fedbad31000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fedbab29000)
        libunwind.so.8 => /lib64/libunwind.so.8 (0x00007fedba90f000)
        libgflags.so.2.1 => /lib64/libgflags.so.2.1 (0x00007fedba6ee000)
        libglog.so.0 => /lib64/libglog.so.0 (0x00007fedba4be000)
        libqatzip.so.1 => /lib64/libqatzip.so.1 (0x00007fedba2b1000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fedba09b000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fedb9d94000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fedb9a92000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fedb987c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fedb94af000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fedbaf4d000)
        libqat_s.so => /usr/local/lib/libqat_s.so (0x00007fedb91e0000)
        libusdm_drv_s.so => /usr/local/lib/libusdm_drv_s.so (0x00007fedb8fc8000)
        libudev.so.1 => /lib64/libudev.so.1 (0x00007fedb8db2000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007fedb8bad000)
        libdw.so.1 => /lib64/libdw.so.1 (0x00007fedb895e000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fedb875a000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007fedb8555000)
        libelf.so.1 => /lib64/libelf.so.1 (0x00007fedb833d000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007fedb8117000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fedb7f07000)
