### ISSUE TITLE
Compile error on Ubuntu 16.04

### ISSUE THREAD

**Issue by jimmy-huang** [intel/QATzip#4]
I am trying to compile this on Ubuntu, and I am getting this link error:
$ make all install
..
..
gcc qzip.o -o qzip -fstack-protector -fPIC -pie -z relro -z now -Wl,-z,noexecstack -L/home/zhuang1/QAT/QAT1.7.Upstream.L.1.0.3_42/build -Wl,-R/home/zhuang1/QAT/QAT1.7.Upstream.L.1.0.3_42/build /home/zhuang1/QAT/QATzip/src/libqatzip.a -lqat_s -lusdm_drv_s -lz -lpthread
/home/zhuang1/QAT/QATzip/src/libqatzip.a(qatzip.o): In function `qzInit':
qatzip.c:(.text+0x209c): undefined reference to `icp_adf_get_numDevices'
collect2: error: ld returned 1 exit status
Makefile:40: recipe for target 'qzip' failed
make[1]: *** [qzip] Error 1
make[1]: Leaving directory '/home/zhuang1/QAT/QATzip/utils'
Makefile:93: recipe for target 'qzip' failed
make: *** [qzip] Error 2

I don't see icp_adf_get_numDevices() defined anywhere, any ideas?

**Comment by jimmy-huang** [comment]
Mine is undefined:
root@otc-tme-wf-04:/home/zhuang1/QAT/QATzip# objdump -t src/libqatzip.so | grep icp_adf
0000000000000000         *UND*	0000000000000000              icp_adf_get_numDevices

@daweiq Well, I do have the L.1.0.3_42 driver on my system, and infact when I do
./configure --with-ICP_ROOT=$ICP_ROOT

, I see the following:
Checking for ICP_ROOT:/home/zhuang1/QAT/QAT1.7.Upstream.L.1.0.3_42... OK
Checking for /home/zhuang1/QAT/QAT1.7.Upstream.L.1.0.3_42/quickassist/include/cpa.h... OK
Checking for /home/zhuang1/QAT/QAT1.7.Upstream.L.1.0.3_42/quickassist/include/dc/cpa_dc.h... OK
Checking for /home/zhuang1/QAT/QAT1.7.Upstream.L.1.0.3_42/quickassist/lookaside/access_layer/include/icp_sal_poll.h... OK
Checking for /home/zhuang1/QAT/QAT1.7.Upstream.L.1.0.3_42/quickassist/lookaside/access_layer/include/icp_sal_user.h... OK
Checking for /home/zhuang1/QAT/QAT1.7.Upstream.L.1.0.3_42/quickassist/utilities/libusdm_drv/qae_mem.h... OK

**Comment by daweiq** [comment]
Good suggestion, I will add this into the backlog.
