### ISSUE TITLE
Can the c3xx series support qatzip tools?

### ISSUE THREAD

**Issue by LhxVinCent** [intel/QATzip#46]
I want to compress one file into another file by qat that is c3xx series but i dont know how to use.    
How can i  use qatzip to  compress  file  that is 1g  size.
           thank you!!!

**Comment by feixuex** [comment]
Please refer to [README.md](https://github.com/intel/QATzip/blob/master/README.md) and [docs/QATzip-man.pdf](https://github.com/intel/QATzip/blob/master/docs/QATzip-man.pdf)

**Comment by zhangp8x** [comment]
reference code can be found in utils
