### ISSUE TITLE
doCompressOut's behavior does not match doDecompressIn/doDecompressOut

### ISSUE THREAD

**Issue by leonzzz** [intel/QATzip#47]
This mismatch does not impact default behavior with default compress format, but it should not be correct logically. 

doCompressOut:

> 

                    outputFooterGen(qz_sess, resl, data_fmt);
                    qz_sess->next_dest += outputFooterSz(data_fmt);    <<<< outputFooterSz(data_fmt) could be zero
                    qz_sess->qz_out_len += outputFooterSz(data_fmt);   <<<< outputFooterSz(data_fmt) could be zero

doDecompressIn:
>
            src_avail_len -= (outputHeaderSz(data_fmt) + src_send_sz + stdGzipFooterSz()); <<<< stdGzipFooterSz()
            dest_avail_len -= dest_receive_sz;

            dest_ptr += dest_receive_sz;

            src_ptr += (src_send_sz + stdGzipFooterSz());    <<<<  stdGzipFooterSz() >0 always
            remaining -= (src_send_sz + stdGzipFooterSz());  <<<<< stdGzipFooterSz() >0 always 

doDecompressOut:
 >
               qz_sess->next_dest += resl->produced;
                qz_sess->qz_in_len += (outputHeaderSz(data_fmt) + src_send_sz +
                                       stdGzipFooterSz());

**Comment by zhangp8x** [comment]
@leonzzz 

Could you please add more information and submit merge request with sign-off-by?

The commit message in the pull request does not contain "Signed-off-by:" in it adhering to license and Developer Certification of Origin.
Could you please update the pull request commit message with "Signed-off-by:" in the following format
Signed-off-by: Name
Note: You are required to use your real name in the sign-off message.

**Comment by cfzhu** [comment]
release in 1.0.7
