### ISSUE TITLE
qaeOpenFd:772 Unable to initialize memory file handle /dev/usdm_drv

### ISSUE THREAD

**Issue by srikanth1986** [intel/QATzip#48]
On after installing the QAT drivers and the QATzip as per instructions, when I try to run the test application I get the following error:
./test -m 3
qaeOpenFd:772 Unable to initialize memory file handle /dev/usdm_drv
qaeOpenFd:772 Unable to initialize memory file handle /dev/usdm_drv
Error no hardware, switch to SW if permitted
g_process.qz_init_status = QZ_NO_HW
Error from pthread_exit qzInit failed

I do have the QAT card present in the server. OS is RedHat 7.4

**Comment by zhangp8x** [comment]
@srikanth1986 Once finished install driver, you have to use `service qat_service status` to check if driver is available.
Then you need to replace the driver configuration file under /etc/c6xx_devX.conf or /etc/dhc895xx_dev0.conf(depend your QAT card's type) with the configuration files under $QATzip/config. and use `service qat_service restart` to enable your configuration.

Notice: 

- QATzip use [SHIM] as default.
- For detail information, please follow README.md. 

If you still need more help, you need to provide the result of  `service qat_service status`

**Comment by zhangp8x** [comment]
@srikanth1986 No response from you, issue closed.
