### ISSUE TITLE
ADF_UIO_PROXY err: icp_adf_userProcessToStart: Error reading /dev/qat_dev_processes file

### ISSUE THREAD

**Issue by srikanth1986** [intel/QATzip#49]
When I try to run qzip, i'm facing this error:
qzip -k silesia.tar
ADF_UIO_PROXY err: icp_adf_userProcessToStart: Error reading /dev/qat_dev_processes file
Error userStarMultiProcess(-1), switch to SW if permitted
g_process.qz_init_status = QZ_NO_HW

How can I fix the same?

**Comment by zhangp8x** [comment]
No QAT card detected, you need to confirm your QAT card is plugged in.
Then, please install the QAT driver, and change [SSL] to [SHIM], make sure you have dc service enabled.

Go to https://01.org/intel-quickassist-technology, to learn the correct way to configure QAT driver.

**Comment by srikanth1986** [comment]
The card is very much detected as shown below.
lspci -d:37c8
3d:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
3f:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
41:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)

Then again towards end of QAT driver installation, I get:
There is 3 QAT acceleration device(s) in the system:
 qat_dev0 - type: c6xx,  inst_id: 0,  node_id: 0,  bsf: 0000:3d:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev1 - type: c6xx,  inst_id: 1,  node_id: 0,  bsf: 0000:3f:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev2 - type: c6xx,  inst_id: 2,  node_id: 0,  bsf: 0000:41:00.0,  #accel: 5 #engines: 10 state: up

Then I follow all instructions from https://github.com/intel/QATzip for Install QATzip As Root User
Including copying the .conf files with [SHIM] section to /etc/ and restarting qat_service

Then I get the error I mentioned in the first post:
qzip -k silesia.tar
ADF_UIO_PROXY err: icp_adf_userProcessToStart: Error reading /dev/qat_dev_processes file
Error userStarMultiProcess(-1), switch to SW if permitted
g_process.qz_init_status = QZ_NO_HW

---------
Alternately, if I do 
./configure --enable-icp-sriov=host
instead of just 
./configure 
during the first step of QAT driver installation, with every other step being the same, the error when testing the application is different as below:

qzip -k silesia.tar
[error] SalCtrl_AdfServicesStartedCheck() - : Sal Ctrl failed to start in given time

[error] do_userStart() - : Failed to start services

Error userStarMultiProcess(-1), switch to SW if permitted
g_process.qz_init_status = QZ_NO_HW


--------
You also mentioned enabling dc service, but I don't see any specific instructions for that. In the past was able to have a working setup just with the above steps. Let me know if I missed anything.

**Comment by zhangp8x** [comment]
@srikanth1986 Please share your driver configuration file.

it is /etc/c6xx_dev0.conf and /etc/c6xx_dev1.conf /etc/c6xx_dev2.conf

**Comment by zhangp8x** [comment]
./configure --enable-icp-sriov=host is only for VF, virtual machine. 

QZ_NO_HW means you do not have QAT hardware, so it must your driver configuration wrong.

**Comment by zhangp8x** [comment]
https://01.org/sites/default/files/downloads//336210-017-intel-qat-programmers-guide-v1.7.pdf is reference for you.

**Comment by zhangp8x** [comment]
@srikanth1986 Sorry for replying late, if no response from you, issue would be closed after 14 days.

**Comment by srikanth1986** [comment]
./configure --enable-icp-sriov=host was only an alternative thing I tried
Anyhow, I think the solution is to disable IOMMU for kernel mode driver to work

**Comment by zhangp8x** [comment]
@srikanth1986 

Yes, you got the correct solution. It should be driver related issue.
In https://01.org/intel-quickassist-technology, it told user: only if you want to enable virtual machine, that you can enable iommu, else iommu should be off.

Thank  you for your reply, have a good day.
