### ISSUE TITLE
When does qatzip depend on the latest version of QAT driver?

### ISSUE THREAD

**Issue by hualongfeng** [intel/QATzip#52]
qatzip depends on QAT driver from the link https://01.org/intel-quickassist-technology. 
But the latest QAT driver is from https://www.intel.com/content/www/us/en/download/19081/intel-quickassist-technology-intel-qat-driver-for-linux-for-intel-server-boards-and-systems-based-on-intel-62x-chipset.html.

When does qatzip depend on the latest version of QAT driver?

**Comment by cfzhu** [comment]
The QATzip supports the latest driver of QAT.
Here is the link https://www.intel.com/content/www/us/en/download/19734/intel-quickassist-technology-driver-for-linux-hw-version-1-7.html. The version is 4.16.0-00017.
the driver of second link is for c62x chipset. its version is 4.14.0-00031.

**Comment by hualongfeng** [comment]
OK, thanks
