### ISSUE TITLE
why "can not detect int size"?

### ISSUE THREAD

**Issue by lulin2008** [intel/QATzip#55]
./configure \
--prefix=$NGINX_INSTALL_DIR \
--without-http_rewrite_module \
--with-http_ssl_module \
--with-http_stub_status_module \
--with-http_v2_module \
--with-stream \
--with-stream_ssl_module \
--add-dynamic-module=modules/nginx_qatzip_module \
--add-dynamic-module=modules/nginx_qat_module/ \
--with-cc-opt="-DNGX_SECURE_MEM -I$OPENSSL_LIB/include -I$QZ_ROOT/include -Wno-error=deprecated-declarations" \
--with-ld-opt="-Wl,-rpath=$OPENSSL_LIB/lib -L$OPENSSL_LIB/lib -L$QZ_ROOT/src -lqatzip -lz"

checking for OS
 + Linux 3.10.0-693.el7.x86_64 x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
checking for gcc -pipe switch ... found
checking for --with-ld-opt="-Wl,-rpath=/etc/nginx/.openssl/lib -L/etc/nginx/.openssl/lib -L/usr/local/src/QATzip-v1.0.7/src -lqatzip -lz" ... found
checking for -Wl,-E switch ... found
checking for gcc builtin atomic operations ... found but is not working
checking for C99 variadic macros ... found but is not working
checking for gcc variadic macros ... found but is not working
checking for gcc builtin 64 bit byteswap ... found
checking for unistd.h ... found
checking for inttypes.h ... found
checking for limits.h ... found
checking for sys/filio.h ... not found
checking for sys/param.h ... found
checking for sys/mount.h ... found
checking for sys/statvfs.h ... found
checking for crypt.h ... found
checking for Linux specific features
checking for epoll ... found but is not working
checking for O_PATH ... found
checking for sendfile() ... found but is not working
checking for sendfile64() ... found but is not working
checking for sys/prctl.h ... found
checking for prctl(PR_SET_DUMPABLE) ... found but is not working
checking for prctl(PR_SET_KEEPCAPS) ... found but is not working
checking for capabilities ... found
checking for crypt_r() ... found
checking for sys/vfs.h ... found
checking for nobody group ... found
checking for poll() ... found
checking for /dev/poll ... not found
checking for kqueue ... not found
checking for crypt() ... not found
checking for crypt() in libcrypt ... found
checking for F_READAHEAD ... not found
checking for posix_fadvise() ... found
checking for O_DIRECT ... found
checking for F_NOCACHE ... not found
checking for directio() ... not found
checking for statfs() ... found
checking for statvfs() ... found
checking for dlopen() ... not found
checking for dlopen() in libdl ... found
checking for sched_yield() ... found
checking for sched_setaffinity() ... found
checking for SO_SETFIB ... not found
checking for SO_REUSEPORT ... found
checking for SO_ACCEPTFILTER ... not found
checking for SO_BINDANY ... not found
checking for IP_TRANSPARENT ... found
checking for IP_BINDANY ... not found
checking for IP_BIND_ADDRESS_NO_PORT ... not found
checking for IP_RECVDSTADDR ... not found
checking for IP_SENDSRCADDR ... not found
checking for IP_PKTINFO ... found
checking for IPV6_RECVPKTINFO ... found
checking for TCP_DEFER_ACCEPT ... found
checking for TCP_KEEPIDLE ... found
checking for TCP_FASTOPEN ... found
checking for TCP_INFO ... found
checking for accept4() ... found
checking for int size ...objs/autotest: error while loading shared libraries: libqatzip.so.1: cannot open shared object file: No such file or directory
  bytes

./configure: error: can not detect int size

**Comment by cfzhu** [comment]
Did you build and install qatzip?

**Comment by lulin2008** [comment]
yes,  l can find  "libqatzip.so.1 "
# find /usr/local/  -name libqatzip.so.1    
/usr/local/src/QATzip-v1.0.7/src/libqatzip.so.1  #soure code
/usr/local/QATzip/lib64/libqatzip.so.1         #installed 

Qat_zip install

**Comment by cfzhu** [comment]
could you add /usr/local/QATzip/lib64/ into LD_LIBRARY_PATH?
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/QATzip/lib64/
```

**Comment by lulin2008** [comment]
thank you very much,This problem has been resolved.
