### ISSUE TITLE
the option --with-ICP_ROOT of configure do not work

### ISSUE THREAD

**Issue by yiwang79** [intel/QATzip#63]
1. put qat driver code in some folder except default path /opt/intel/QAT/quickassist
2. execute ./configure --with_ICP_ROOT=/path_to_driver.  It will report "configure: error: not found qat header files".

**Comment by XingHongChenIntel** [comment]
hello wang. very thanks for your comments.
This issue will be fixed in qatzip v1.0.9

**Comment by cfzhu** [comment]
fixed in qatzip v1.0.9
