### ISSUE TITLE
about the doCompressOut

### ISSUE THREAD

**Issue by weeweetan** [intel/QATzip#66]
version:1.0.6
doCompressOut executes this if branch 
`if (unlikely(CPA_DC_VERIFY_ERROR == resl->status)) {...}`
I read the qat driver related code, but I didn't find the following code
`pResults->status = CPA_DC_VERIFY_ERROR`
`status = CPA_DC_VERIFY_ERROR`

I want to know in what scenario, the value of status will be assigned to **CPA_DC_VERIFY_ERROR**

**Comment by cfzhu** [comment]
hi @weeweetan, the error code will be set to CPA_DC_VERIFY_ERROR when QAT device enable CnV(compression and verify), 
CnV is done to verify the integrity of the compressed data by comparing the CRCs of the clear text and the size of the clear text. 
the DCPR(Decompression Slice ) decompress a compressed block in order to compute the CRCs, and the DCPR output CRCs is compared against the CPR(Compression Slice) input CRCs to verify the integrity of the compressed block. if verification failed,
QAT will set the response message error code to CPA_DC_VERIFY_ERROR.
here is the code to get compression error code from response message in driver function dcCompression_ProcessCallback(), 
    /* Get the cmp error code */
    cmpErr = pCompRespMsg->comn_resp.comn_error.s1.cmp_err_code;

**Comment by weeweetan** [comment]
hi @cfzhu 
> the DCPR(Decompression Slice ) decompress a compressed block in order to compute the CRCs, and the DCPR output CRCs is compared against the CPR(Compression Slice) input CRCs to verify the integrity of the compressed block. if verification failed, QAT will set the response message error code to CPA_DC_VERIFY_ERROR.

Does this error occur because there are special characters in the source data, or is the source data rewritten?

**Comment by cfzhu** [comment]
> 
I don't think this is due to special characters, for source data rewritten, I haven't considered this case, it may cause this error, but I am not sure. Did you encounter this error?

**Comment by weeweetan** [comment]
@cfzhu yes,  qz_sess->next_dest assignment error in version 1.0.6
`//Append footer
outputFooterGen(qz_sess, resl, data_fmt);
qz_sess->next_dest += stdGzipFooterSz();`
and then the following code triggers coredump
`assert(*dest_len == sess->total_out);`

so I want to know what scenario can this error occur
> the DCPR(Decompression Slice ) decompress a compressed block in order to compute the CRCs, and the DCPR output CRCs is compared against the CPR(Compression Slice) input CRCs to verify the integrity of the compressed block. if verification failed, QAT will set the response message error code to CPA_DC_VERIFY_ERROR.

**Comment by cfzhu** [comment]
> @cfzhu yes, qz_sess->next_dest assignment error in version 1.0.6 `//Append footer outputFooterGen(qz_sess, resl, data_fmt); qz_sess->next_dest += stdGzipFooterSz();` and then the following code triggers coredump `assert(*dest_len == sess->total_out);`
> 
> so I want to know what scenario can this error occur
> 
> > the DCPR(Decompression Slice ) decompress a compressed block in order to compute the CRCs, and the DCPR output CRCs is compared against the CPR(Compression Slice) input CRCs to verify the integrity of the compressed block. if verification failed, QAT will set the response message error code to CPA_DC_VERIFY_ERROR.

i don't think core dump is due to CPA_DC_VERIFY_ERROR, this may be same issue https://github.com/intel/QATzip/issues/50 
https://github.com/intel/QATzip/issues/47
