### ISSUE TITLE
QATzip Unable to Find Hardware

### ISSUE THREAD

**Issue by asnys** [intel/QATzip#7]
I am trying to install QATzip on a box with a QuickAssist 8950. I was able to compile it successfully, but when I run it, I get a message:

`"Error no hardware, switch to SW if permitted"`

The machine is not virtualized; the intent is to eventually run QATzip inside a (single) Docker container, but I'm currently just trying to get it to work outside of Docker. I am guessing the problem is due to the QAT driver: I built and installed the driver from the 01.org website, but when I run:

`service qat_service start`

I see the following error message:

`[ 1343.743455] dh895xcc 0000:0c:00.0: Cannot use PF with IOMMU enabled`

I tried adding `intel_iommu=off` to grub, but this made no difference. When I run `service qat_service status`, it reports that it _is_ able to see the QAT acceleration device. I'd greatly appreciate any assistance you can provide.

**Comment by daweiq** [comment]
@asnys 

The "no hardware" info showing QATzip cannot get HW instance for acceleration, it might because of the driver issue or the QAT configuration issue. 
May I know the driver version and the QAT config file you are using?

Thanks, 
David

**Comment by asnys** [comment]
The versionfile in the qat driver says it is version 4.3.0. By QAT config file, do you mean the config file in /etc? I am using the thread-optimized version of dh895xcc_dev0.conf from the QATZip repo.

**Comment by daweiq** [comment]
The intel_iommu should be turned off when using PF on host because we don't support huge pages when the iommu is on.
Does the "Cannot use PF with IOMMU enabled" error still shows even after you disable the intel_iommu? 
If yes, it might because of the iommu is still on or the VF is used in host.

**Comment by asnys** [comment]
I tried adding "iommu=off" to grub, and it no longer shows the `"Cannot Use PF with IOMMU enabled"` message when I start qat_service. However, it still does not actually work. Now, when I start the qat_service, I get one or more messages saying:

`dh895xccvf 0000:0c:027: Spurious PF2VF interrupt. msg 40CA. Ignored`

The number of messages and the string after `msg` varies. When I run qzip, it still says:

`Error no hardware, switch to SW if permitted`

Thank you very much for your help!

**Comment by daweiq** [comment]
It seems the VF is enabled on your host.
Would you please run the "adf_ctl status" to check any VF function enabled on your host? 
Besides, would you please run "lsmod | grep qat" to check is there any qat VF driver installed?

**Comment by asnys** [comment]
When I run `adf_ctl status`, I get:

```
qat_dev0 - type: dh895xcc,  inst_id: 0,  node_id: 0, bsf: 0c:00.0,  #accel: 6 #engines: 12 state: up
qat_dev1 - type: dh895xccvf,  inst_id: 0,  node_id: 0, bsf: 0c:01.0,  #accel: 1 #engines: 1 state: down
qat_dev2 - type: dh895xccvf,  inst_id: 1,  node_id: 0, bsf: 0c:01.1,  #accel: 1 #engines: 1 state: down
qat_dev3 - type: dh895xccvf,  inst_id: 2,  node_id: 0, bsf: 0c:01.2,  #accel: 1 #engines: 1 state: down
```

That then continues to `qat_dev32`.

When I run lsmod | grep qat, I get:

```
qat_dh895xccvf     16384  0
qat_dh895xcc       20480  0
intel_qat         229376  3 qat_dh895xcc,qat_dh895xccvf,usdm_drv
uio                20480  1 intel_qat
authenc            16384  1 intel_qat
```

**Comment by daweiq** [comment]
It seems the qat_dh895xccvf VF driver stopped the QATzip.
Would you please try re-configure the driver with "./configure" command ?
And leave SRIOV disabled. 
Then, rebuild the QATzip library.

**Comment by daweiq** [comment]
After rebuild the the driver, the QAT configure file under /etc folder will be replaced to default version by `make install` command. Please make sure to use the QATzip recommend multiple-thread/multiple-process config file which including the `[SHIM]` section. 
Besides, the USDM driver should be configured to enabled huge-page support, if the `cat /proc/meminfo` command does not show any hugepage available, please re-enable it with the following command:
```
    echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
    rmmod usdm_drv
    insmod $ICP_ROOT/build/usdm_drv.ko max_huge_pages=1024 max_huge_pages_per_process=16
```

**Comment by asnys** [comment]
I recopied the QAT configure file to /etc and restarted qat_service, but this had no effect. I checked in vim and it does include the `[SHIM]` section:

```
[SHIM]
NumberCyInstances = 0
NumberDcInstances = 4
NumProcesses = 8
LimitDevAccess = 1

# Data Compression - User Instance #0
Dc0Name = "Dc0"
Dc0IsPolled = 1
# List of core affinities
Dc0CoreAffinity = 1

# Data Compression - User Instance #1
Dc1Name = "Dc1"
Dc1IsPolled = 1
# List of core affinities
Dc1CoreAffinity = 1

# Data Compression - User Instance #2
Dc2Name = "Dc2"
Dc2IsPolled = 1
# List of core affinities
Dc2CoreAffinity = 2

# Data Compression - User Instance #3
Dc3Name = "Dc3"
Dc3IsPolled = 1
# List of core affinities
Dc3CoreAffinity = 3
```

Hugepage support does appear to be enabled. When I run `cat /proc/meminfo | grep Hugepage`, I get:

`Hugepagesize:     2048 kB`

And when I run `cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages`, I get:

`1024`

Just to be sure, I reran the commands to configure USDM to enable hugepage support. This had no effect.

**Comment by asnys** [comment]
I'm not sure if this is relevant, but I tried running qzip as root, and I got a slightly different message. Previously, the exact message I got was:

```
Error no hardware, switch to SW if permitted
g_process.qz_init_status = QZ_NO_HW
Reading input file test.txt (5 bytes)
Compressing...
Time taken:        0.077 s
Throughput:        0.519 Mbit/s
Space Savings:  -680.000 %
Compression ratio: 0.128 : 1
```

When I run it as sudo, I get:

```
g_process.qz_init_status = QZ_NO_HW
Reading input file test.txt (5 bytes)
Compressing...
g_process.qz_init_status = QZ_NO_HW
Time taken:        0.077 s
Throughput:        0.519 Mbit/s
Space Savings:  -680.000 %
Compression ratio: 0.128 : 1
```

**Comment by daweiq** [comment]
The error info 
```
Error no hardware, switch to SW if permitted
```

Printed because the driver return no PCIE device in qzInit
```
int qzInit(QzSession_T *sess, unsigned char sw_backup)
{
   ...
    status = icp_adf_get_numDevices(&g_process.pcie_count);
    if (CPA_STATUS_SUCCESS != status) {
        g_process.pcie_count = 0;
    }

    if (0 == g_process.pcie_count) {
        QZ_ERROR("Error no hardware, switch to SW if permitted\n", status);
        BACKOUT;
    }
    ...
```
It seems the driver/HW  does not work well.

**Comment by asnys** [comment]
I went through the full process of uninstalling and reinstalling QATZip and the QAT driver. I'll lay it out here in case it will help someone in the future; specifically, I:

1. Ran `make uninstall` in both the QATZip and QAT driver directories.

2. Deleted both the QATZip and QAT driver directories and replaced them with clean copies from my archived tarfiles.

3. Verified that the environment variable `ICP_ROOT` is still set to the correct directory.

4. Configured the QAT driver with the command:

`./configure ICP_ROOT=$ICP_ROOT `

5. Built and installed the QAT driver with the command `make install`.

6. Verified that the environment variable `QATZIP_ROOT` is still set to the correct directory.

7. Verified that hugepages is still set correctly by running:

`cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages`

Which returned 1024.

8. Ran the commands:

```
rmmod usdm_drv
insmod $ICP_ROOT/build/usdm_drv.ko max_huge_pages=1024 max_huge_pages_per_process=16
```

9. Configured QATZip with the command:

`bash ./configure --with-ICP_ROOT=$ICP_ROOT`

10. Built QATZip with the commands:

```
make clean
make all install
```

11. Updated the QAT driver configuration file by copying:

`cp $QATZIP_ROOT/config_file/dh895xcc/multiple_process_opt/dh895xcc_dev0.conf /etc`

12. Restarted the QAT driver by running `service qat_service restart`.

And after all that... Tried running qzip as sudo. And it worked! :) I must have, at some point in this process, set a flag or something wrong somewhere and then failed to notice, but jogged it loose by just redoing everything from scratch. Thanks very much for your help!

**Comment by yangni2017** [comment]
@daweiq hi~ i want to know There is no other way to use the hardware instead of set iommu off? because i need the iommu keep on.
