### ISSUE TITLE
Need configuration files for 4xxx devices

### ISSUE THREAD

**Issue by iomartin** [intel/QATzip#73]
Hello,

This repo needs the configuration files for 4xxx devices. I tried using the 3xxx configuration and it worked, but I don't know if that is an optimal configuration.

**Comment by iomartin** [comment]
Just to make clear, there are configuration files for performance testing (`test/performance_tests/config_file/4xxx`) but the repo is missing the general multiple_process_opt/multiple_thread_opt conf files (`config_file/<PLATFORM>/`)

**Comment by iomartin** [comment]
Interesting, my platform (as I described on #75) only has 2 endpoints. It is an Intel(R) Xeon(R) Platinum 8480+.

I will use the configuration from the test/performance_tests/config_file/4xxx if those are considered a good setup.

**Comment by mythi** [comment]
> This repo needs the configuration files for 4xxx devices.

The (better) alternative would be to use `qatlib` which means the config files are not needed.

**Comment by iomartin** [comment]
@mythi Thanks for pointing me to `qatlib`, does it not need config files at all or does it just not need the updated versions included in this repo (with the [SHIM] section)?

**Comment by mythi** [comment]
@iomartin it does not need config files at all

**Comment by iomartin** [comment]
Cool! I've noticed that my 4940s have 9 engines, but using the provided configurations and some permutations I tried, only 8 are ever active (I only enable the `dc` service). I checked this via the fw_counters.

Would qatlib be able to use all 9 engines? Or would you know how to enable the 9th engine via the conf files? I'm trying to get some baseline numbers.

**Comment by gcabiddu** [comment]
In 4xxx, the 9th engine is an admin engine and cannot be used for crypto and/or compression services.

**Comment by cfzhu** [comment]
Update 4xxx config file https://github.com/intel/QATzip/commit/f281c31e678f553fd1d358a1614ad7ac93c4ff28
