### ISSUE TITLE
perf test with SVM will crash

### ISSUE THREAD

**Issue by guoanwu** [intel/QATzip#78]
crash happen in the code main.c:1266
    if (g_perf_svm ) {
        memcpy(src, ((TestArg_T *)arg)->src, src_sz);
    }
should change to:
    if (g_perf_svm && g_input_file_name) {
        memcpy(src, ((TestArg_T *)arg)->src, src_sz);
    }

Starting program: /home/dennis/qatzip/test/test -m 4 -l 100000 -t 1 -D comp -M svm
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".

Breakpoint 1, main (argc=11, argv=0x7fffffffe1c8) at main.c:3874
3874    {
(gdb) b 1254
Breakpoint 2 at 0x5555554098f4: file main.c, line 1254.
(gdb) c
Continuing.
[New Thread 0x7ffff580c700 (LWP 705037)]

Thread 2 "test" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff580c700 (LWP 705037)]
0x00007ffff700c6d3 in __memmove_avx_unaligned_erms () from /usr/lib64/libc.so.6
(gdb) bt
#0  0x00007ffff700c6d3 in __memmove_avx_unaligned_erms () from /usr/lib64/libc.so.6
#1  0x0000555555409b4a in memcpy (__len=524288, __src=<optimized out>, __dest=0x7ffff000e6c0) at /usr/include/bits/string_fortified.h:34
#2  qzCompressAndDecompress (arg=0x7fffffffab80) at main.c:1266
#3  0x00007ffff727917a in start_thread () from /usr/lib64/libpthread.so.0
#4  0x00007ffff6fa8dc3 in clone () from /usr/lib64/libc.so.6

**Comment by cfzhu** [comment]
updated code https://github.com/intel/QATzip/commit/0b101905ea36183cafef05d35c9760e35cb43bbb
