### ISSUE TITLE
if the compressed buffer size is over the original buffer, stream decompress failed wit error code -2

### ISSUE THREAD

**Issue by guoanwu** [intel/QATzip#79]
get decompress param:buffer len = 262453, mpa.pages=64
before DecompressStream in: 0x7f80a3c01400, out:0x7f80bbf01000,  in_size: 262144, out_sz: 262144, last: 0
in buffer start value:x4088b1f
in buffer end value:x4c312700fab8243e
Decompress Stream Start...
Copy to input from 0x7f80a3c01400, to 0x7f80a3c81400, count 262144
Before Call qzDecompress input_len 262144 output_len 262144 stream->pending_in 262144 stream->pending_out 0 stream->in_sz 0 stream->out_sz 262144
qzDecompress data_fmt: 2
qzDecompress: inst is 0
Find 0x7f80a3c81000 in page table
Find 0x7f80a3cc1000 in page table
doDecompressIn: Need to g_process 262144 bytes
src_avail_len is 262144, dest_avail_len is 262144
getUnusedBuffer returned 0
doDecompressIn: Sending 65070 bytes starting at 0x7f80a3c81418
sending seq number 0 0 17
Decomp Sending i = 0 j = 0 seq = 16 tag = 0
mw>> doDecompressIn():  DcDecompressData() rc = 0
src_ptr is 0x7f80a3c9124e, remaining is 197042
src_avail_len is 197042, dest_avail_len is 196970
getUnusedBuffer returned 1
doDecompressIn: Sending 0 bytes starting at 0x7f80a3c91266
sending seq number 0 1 18
Decomp Sending i = 0 j = 1 seq = 17 tag = 1
[error] dcCheckSourceData() - : Invalid API Param - The source buffer size needs to be greater than zero bytes for stateless sessions
mw>> doDecompressIn():  DcDecompressData() rc = -4
Error in cpaDcCompressData: -4
mw>> function doDecompressOut() called
decomp sleep for 10 usec...
decomp sleep for 20 usec...
doDecompressOut: Processing seqnumber 00 00 0016
Decomp sleep_cnt: 2
PRoduced 0 bytes
total_in=0 total_out=0 src_len=0 dest_len=0 rc=-2 src_len=0 dest_len=0
Return code = -2
Exit Decompress Stream input_len 0 output_len 0 stream->pending_in 262144 stream->pending_out 0 stream->in_sz 0 stream->out_sz 0
qemu-system-x86_64: ERROR: Decompress FAILED with return value: -2

**Comment by guoanwu** [comment]
++ This is the compress side debug output. compress w/o any issue. 
before compress in buffer start value:x0
before compress in buffer end value:x69d3e4d8c2783164
Copy to input from 0x7f742ff01000, to 0x7f7403e1d400, count 65536
Before Call qzCompressCrc input_len 65536 output_len 65536 stream->pending_in 65536 stream->pending_out 0 stream->in_sz 196608 stream->out_sz 262144
qzCompressCrc data_fmt: 2, input crc32 is 0x5278A43C
qzCompress: inst is 0
Always enable CnV
Find 0x7f7403e1d000 in page table
Find 0x7f7403e2d000 in page table
doCompressIn: Need to g_process 65536 bytes
getUnusedBuffer returned 0
sending seq number 0 0 0, opData.flushFlag 1
changing src_ptr to 0x7f7403e1d400
Comp Sending 65536 bytes ,opData.flushFlag = 1, i = 0 j = 0 seq = 0 tag = 0
remaining = 65536, src_send_sz = 65536, seq = 1
comp sleep for 200 usec...
doCompressOut: Processing seqnumber 00 00 0000, PID: 2582320, TID: 140136257533696
        consumed = 65174, produced = 65070, seq_in = 0
Generate header
crc32 input 0x5278A43C, Result 0xEC4797CE, checksum 0x8B07A92B, consumed 65174, produced 65070
Comp sleep_cnt: 1
PRoduced 65102 bytes

********* total_in = 65174 total_out = 65102 src_len = 65174 dest_len = 65102
copy 65102 to user output
After Call qzCompressCrc input_len 65174 output_len 65102 stream->pending_in 362 stream->pending_out 0 stream->in_sz 196608 stream->out_sz 197042
Before Call qzCompressCrc input_len 362 output_len 65536 stream->pending_in 362 stream->pending_out 0 stream->in_sz 196608 stream->out_sz 197042
qzCompressCrc data_fmt: 2, input crc32 is 0xEC4797CE
compression src_len=362, sess_params.input_sz_thrshold = 1024, process.qz_init_status = 0, sess->hw_session_stat = 0,  switch to software.
copy 396 to user output
After Call qzCompressCrc input_len 362 output_len 396 stream->pending_in 0 stream->pending_out 0 stream->in_sz 196608 stream->out_sz 196646
Copy to input from 0x7f742ff11000, to 0x7f7403e1d400, count 65536
Before Call qzCompressCrc input_len 65536 output_len 65536 stream->pending_in 65536 stream->pending_out 0 stream->in_sz 131072 stream->out_sz 196646
qzCompressCrc data_fmt: 2, input crc32 is 0x1DCF1ACB
qzCompress: inst is 0
Always enable CnV
Find 0x7f7403e1d000 in page table
Find 0x7f7403e2d000 in page table
doCompressIn: Need to g_process 65536 bytes
getUnusedBuffer returned 0
sending seq number 0 0 0, opData.flushFlag 1
changing src_ptr to 0x7f7403e1d400
Comp Sending 65536 bytes ,opData.flushFlag = 1, i = 0 j = 0 seq = 0 tag = 0
remaining = 65536, src_send_sz = 65536, seq = 1
comp sleep for 200 usec...
doCompressOut: Processing seqnumber 00 00 0000, PID: 2582320, TID: 140136257533696
        consumed = 65001, produced = 65074, seq_in = 0
Generate header
crc32 input 0x1DCF1ACB, Result 0xEBC9ABBF, checksum 0xF093B568, consumed 65001, produced 65074
Comp sleep_cnt: 1
PRoduced 65106 bytes

********* total_in = 65001 total_out = 65106 src_len = 65001 dest_len = 65106
copy 65106 to user output
After Call qzCompressCrc input_len 65001 output_len 65106 stream->pending_in 535 stream->pending_out 0 stream->in_sz 131072 stream->out_sz 131540
Before Call qzCompressCrc input_len 535 output_len 65536 stream->pending_in 535 stream->pending_out 0 stream->in_sz 131072 stream->out_sz 131540
qzCompressCrc data_fmt: 2, input crc32 is 0xEBC9ABBF
compression src_len=535, sess_params.input_sz_thrshold = 1024, process.qz_init_status = 0, sess->hw_session_stat = 0,  switch to software.
copy 545 to user output
After Call qzCompressCrc input_len 535 output_len 545 stream->pending_in 0 stream->pending_out 0 stream->in_sz 131072 stream->out_sz 130995
Copy to input from 0x7f742ff21000, to 0x7f7403e1d400, count 65536
Before Call qzCompressCrc input_len 65536 output_len 65536 stream->pending_in 65536 stream->pending_out 0 stream->in_sz 65536 stream->out_sz 130995
qzCompressCrc data_fmt: 2, input crc32 is 0x8EB5605
qzCompress: inst is 0
Always enable CnV
Find 0x7f7403e1d000 in page table
Find 0x7f7403e2d000 in page table
doCompressIn: Need to g_process 65536 bytes
getUnusedBuffer returned 0
sending seq number 0 0 0, opData.flushFlag 1
changing src_ptr to 0x7f7403e1d400
Comp Sending 65536 bytes ,opData.flushFlag = 1, i = 0 j = 0 seq = 0 tag = 0
remaining = 65536, src_send_sz = 65536, seq = 1
comp sleep for 200 usec...
doCompressOut: Processing seqnumber 00 00 0000, PID: 2582320, TID: 140136257533696
        consumed = 65007, produced = 65070, seq_in = 0
Generate header
crc32 input 0x8EB5605, Result 0x734A8785, checksum 0xFEE0E4EF, consumed 65007, produced 65070
Comp sleep_cnt: 1
PRoduced 65102 bytes

********* total_in = 65007 total_out = 65102 src_len = 65007 dest_len = 65102
copy 65102 to user output
After Call qzCompressCrc input_len 65007 output_len 65102 stream->pending_in 529 stream->pending_out 0 stream->in_sz 65536 stream->out_sz 65893
Before Call qzCompressCrc input_len 529 output_len 65536 stream->pending_in 529 stream->pending_out 0 stream->in_sz 65536 stream->out_sz 65893
qzCompressCrc data_fmt: 2, input crc32 is 0x734A8785
compression src_len=529, sess_params.input_sz_thrshold = 1024, process.qz_init_status = 0, sess->hw_session_stat = 0,  switch to software.
copy 539 to user output
After Call qzCompressCrc input_len 529 output_len 539 stream->pending_in 0 stream->pending_out 0 stream->in_sz 65536 stream->out_sz 65354
Copy to input from 0x7f742ff31000, to 0x7f7403e1d400, count 65536
Before Call qzCompressCrc input_len 65536 output_len 65536 stream->pending_in 65536 stream->pending_out 0 stream->in_sz 0 stream->out_sz 65354
qzCompressCrc data_fmt: 2, input crc32 is 0xF747ED9E
qzCompress: inst is 0
Always enable CnV
Find 0x7f7403e1d000 in page table
Find 0x7f7403e2d000 in page table
doCompressIn: Need to g_process 65536 bytes
getUnusedBuffer returned 0
sending seq number 0 0 0, opData.flushFlag 1
changing src_ptr to 0x7f7403e1d400
Comp Sending 65536 bytes ,opData.flushFlag = 1, i = 0 j = 0 seq = 0 tag = 0
remaining = 65536, src_send_sz = 65536, seq = 1
comp sleep for 200 usec...
doCompressOut: Processing seqnumber 00 00 0000, PID: 2582320, TID: 140136257533696
        consumed = 64989, produced = 65071, seq_in = 0
Generate header
crc32 input 0xF747ED9E, Result 0xD79E9E7C, checksum 0x4DF2125E, consumed 64989, produced 65071
Comp sleep_cnt: 1
PRoduced 65103 bytes

********* total_in = 64989 total_out = 65103 src_len = 64989 dest_len = 65103
copy 65103 to user output
After Call qzCompressCrc input_len 64989 output_len 65103 stream->pending_in 547 stream->pending_out 0 stream->in_sz 0 stream->out_sz 251
Before Call qzCompressCrc input_len 547 output_len 65536 stream->pending_in 547 stream->pending_out 0 stream->in_sz 0 stream->out_sz 251
qzCompressCrc data_fmt: 2, input crc32 is 0xD79E9E7C
compression src_len=547, sess_params.input_sz_thrshold = 1024, process.qz_init_status = 0, sess->hw_session_stat = 0,  switch to software.
copy 251 to user output
After Call qzCompressCrc input_len 547 output_len 560 stream->pending_in 0 stream->pending_out 309 stream->in_sz 0 stream->out_sz 0
Exit Compress Stream input_len 547 output_len 560 stream->pending_in 0 stream->pending_out 309 stream->in_sz 262144 stream->out_sz 262144
before compress in buffer start value:x0
before compress in buffer end value:x69d3e4d8c2783164
copy 309 to user output
Exit Compress Stream input_len 0 output_len 0 stream->pending_in 0 stream->pending_out 0 stream->in_sz 0 stream->out_sz 309
dennis: after qzcompressstream: produced=262453

**Comment by guoanwu** [comment]
If set the stream buffer size same in the compress and decompress side. the issue will not happen.

**Comment by daweiq** [comment]
Close the issue since no update
