### ISSUE TITLE
if stream input size is over the stream buffer size, the decompress failed with -4. adjust the stream buffer size can solve.

### ISSUE THREAD

**Issue by guoanwu** [intel/QATzip#80]
get decompress param:buffer len = 66699, mpa.pages=64
before DecompressStream in: 0x7f65fc601400, out:0x7f6617e41000,  in_size: 66699, out_sz: 262144, last: 1
in buffer start value:x4088b1f
in buffer end value:x10000900ba11c
Decompress Stream Start...
Copy to input from 0x7f65fc601400, to 0x7f65fc681400, count 65536
Before Call qzDecompress input_len 65536 output_len 65536 stream->pending_in 65536 stream->pending_out 0 stream->in_sz 1163 stream->out_sz 262144
qzDecompress data_fmt: 2
qzDecompress: inst is 0
Find 0x7f65fc681000 in page table
Find 0x7f65fc691000 in page table
doDecompressIn: Need to g_process 65536 bytes
src_avail_len is 65536, dest_avail_len is 65536
getUnusedBuffer returned 0
doDecompressIn: Sending 421 bytes starting at 0x7f65fc681418
sending seq number 0 0 5
Decomp Sending i = 0 j = 0 seq = 4 tag = 0
mw>> doDecompressIn():  DcDecompressData() rc = 0
src_ptr is 0x7f65fc6815c5, remaining is 65083
src_avail_len is 65083, dest_avail_len is 0
checkHeader: insufficient destation buffer length
src_ptr is 0x7f65fc6815c5, remaining is 0
mw>> function doDecompressOut() called
decomp sleep for 100 usec...
doDecompressOut: Processing seqnumber 00 00 0004
        consumed = 421, produced = 65536, seq_in = 4, src_send_sz = 421
qz_sess->next_dest = 0x7f65fc6a1400
Decomp sleep_cnt: 1
PRoduced 0 bytes
total_in=453 total_out=65536 src_len=453 dest_len=65536 rc=-3 src_len=453 dest_len=65536
Return code = -3
copy 65536 to user output
Copy output 65536 bytes
After Call qzDecompress input_len 453 output_len 65536 stream->pending_in 65083 stream->pending_out 0 stream->in_sz 1163 stream->out_sz 196608
Recoverable buffer error occurs... 
Before Call qzDecompress input_len 65083 output_len 65536 stream->pending_in 65083 stream->pending_out 0 stream->in_sz 1163 stream->out_sz 196608
qzDecompress data_fmt: 2
qzDecompress: inst is 0
Find 0x7f65fc681000 in page table
Find 0x7f65fc691000 in page table
doDecompressIn: Need to g_process 65083 bytes
src_avail_len is 65083, dest_avail_len is 65536
getUnusedBuffer returned 0
doDecompressIn: Sending 421 bytes starting at 0x7f65fc6815dd
sending seq number 0 0 6
Decomp Sending i = 0 j = 0 seq = 5 tag = 0
mw>> doDecompressIn():  DcDecompressData() rc = 0
src_ptr is 0x7f65fc68178a, remaining is 64630
src_avail_len is 64630, dest_avail_len is 0
checkHeader: insufficient destation buffer length
src_ptr is 0x7f65fc68178a, remaining is 0
mw>> function doDecompressOut() called
decomp sleep for 100 usec...
doDecompressOut: Processing seqnumber 00 00 0005
        consumed = 421, produced = 65536, seq_in = 5, src_send_sz = 421
qz_sess->next_dest = 0x7f65fc6a1400
Decomp sleep_cnt: 1
PRoduced 0 bytes
total_in=453 total_out=65536 src_len=453 dest_len=65536 rc=-3 src_len=453 dest_len=65536
Return code = -3
copy 65536 to user output
Copy output 65536 bytes
After Call qzDecompress input_len 453 output_len 65536 stream->pending_in 64630 stream->pending_out 0 stream->in_sz 1163 stream->out_sz 131072
Recoverable buffer error occurs... 
Before Call qzDecompress input_len 64630 output_len 65536 stream->pending_in 64630 stream->pending_out 0 stream->in_sz 1163 stream->out_sz 131072
qzDecompress data_fmt: 2
qzDecompress: inst is 0
Find 0x7f65fc681000 in page table
Find 0x7f65fc691000 in page table
doDecompressIn: Need to g_process 64630 bytes
src_avail_len is 64630, dest_avail_len is 65536
getUnusedBuffer returned 0
doDecompressIn: Sending 17591 bytes starting at 0x7f65fc6817a2
sending seq number 0 0 7
Decomp Sending i = 0 j = 0 seq = 6 tag = 0
mw>> doDecompressIn():  DcDecompressData() rc = 0
src_ptr is 0x7f65fc685c61, remaining is 47007
src_avail_len is 47007, dest_avail_len is 0
checkHeader: insufficient destation buffer length
src_ptr is 0x7f65fc685c61, remaining is 0
mw>> function doDecompressOut() called
decomp sleep for 100 usec...
doDecompressOut: Processing seqnumber 00 00 0006
        consumed = 17591, produced = 65536, seq_in = 6, src_send_sz = 17591
qz_sess->next_dest = 0x7f65fc6a1400
Decomp sleep_cnt: 1
PRoduced 0 bytes
total_in=17623 total_out=65536 src_len=17623 dest_len=65536 rc=-3 src_len=17623 dest_len=65536
Return code = -3
copy 65536 to user output
Copy output 65536 bytes
After Call qzDecompress input_len 17623 output_len 65536 stream->pending_in 47007 stream->pending_out 0 stream->in_sz 1163 stream->out_sz 65536
Recoverable buffer error occurs... 
Before Call qzDecompress input_len 47007 output_len 65536 stream->pending_in 47007 stream->pending_out 0 stream->in_sz 1163 stream->out_sz 65536
qzDecompress data_fmt: 2
qzDecompress: inst is 0
Find 0x7f65fc685000 in page table
Find 0x7f65fc691000 in page table
doDecompressIn: Need to g_process 47007 bytes
src_avail_len is 47007, dest_avail_len is 65536
checkHeader: incomplete source buffer
src_ptr is 0x7f65fc685c61, remaining is 0
mw>> function doDecompressOut() called
decomp sleep for 100 usec...
Decomp sleep_cnt: 1
PRoduced 0 bytes
total_in=0 total_out=0 src_len=0 dest_len=0 rc=-4 src_len=0 dest_len=0
Return code = -4
Exit Decompress Stream input_len 0 output_len 0 stream->pending_in 47007 stream->pending_out 0 stream->in_sz 0 stream->out_sz 196608
qemu-system-x86_64: ERROR: Decompress FAILED with return value: -4

**Comment by XingHongChenIntel** [comment]
hello:
please refer to the README's limitations(https://github.com/intel/QATzip#limitations)
"For stream object, stream length must be smaller than strm_buff_sz, or QATzip would generate multiple deflate block in order and has the last block with BFIN set."
so this is not the Unpredictable issues，customer have to follow the limitation, or as you metioned adjust stream buffer size.
then we will close this ticket.
