### ISSUE TITLE
qatzip stream API, only when the last=1, stream.out_sz update. 

### ISSUE THREAD

**Issue by guoanwu** [intel/QATzip#81]
while (consumed < src_sz) {
            comp_strm.in    = src + consumed;
            comp_strm.out   = dest + produced;
            comp_strm.in_sz = block_size;
            comp_strm.out_sz =  dest_sz - produced;
            last = (src_sz == (consumed + comp_strm.in_sz)) ? 1 : 0;
            rc = qzCompressStream(&sess, &comp_strm, last);
            if (rc != QZ_OK) {
                QZ_ERROR("qzCompressStream FAILED, return: %d", rc);
                goto done;
            }
            consumed += comp_strm.in_sz;
            produced += comp_strm.out_sz;
            QZ_PRINT("comp [%d] consumed= %d, produced = %d\n",
                    k, consumed, produced); 
            if (1 == last && 0 == comp_strm.pending_in
                    && 0 == comp_strm.pending_out) {
                break;
            }
        }

just monitor the produced, you will see the produced always 0, only when the last=1 and then produced value update. 
the output of the code show:
comp [0] consumed= 241664, produced = 0
comp [0] consumed= 245760, produced = 0
comp [0] consumed= 249856, produced = 0
comp [0] consumed= 253952, produced = 0
comp [0] consumed= 258048, produced = 0
comp [0] consumed= 262144, produced = 26468

compress is OK, but for decomp that will cause issue, see the following code:

        while (decomp_size > produced) {
            comp_strm.in    = dest + consumed;
            comp_strm.out   = src + produced;
            comp_strm.in_sz = comp_size - consumed;
            comp_strm.out_sz =  block_size;
            last = ((produced + comp_strm.out_sz) == src_sz) ? 1 : 0;
            rc = qzDecompressStream(&sess, &comp_strm, last);
            if (rc != QZ_OK) {
                QZ_ERROR("qzCompressStream FAILED, return: %d", rc);
                goto done;
            }
            consumed += comp_strm.in_sz;
            produced += comp_strm.out_sz;
            QZ_PRINT("decomp [%d] consumed= %d, produced = %d\n",
                    k, consumed, produced); 
            if (1 == last && 0 == comp_strm.pending_in
                    && 0 == comp_strm.pending_out) {
                break;
            }
        }
This code will under the infinite loop.

**Comment by cfzhu** [comment]
thanks, we are checking this issue.

**Comment by XingHongChenIntel** [comment]
it's not true, stream.out_sz will update when last=1 or pending_in is larger than stream buffer size. it's not only for last=1.

**Comment by daweiq** [comment]
Close the issue since no update
