### ISSUE TITLE
can qatzip install to the default pkg-config directory?

### ISSUE THREAD

**Issue by guoanwu** [intel/QATzip#83]
After qatzip installed, use the "pkg-config --list-all", the qatzip is not in the list. 
We need to set the PKG_CONFIG_PATH and add the qatzip pkg-config path, then we can get qatzip from the "pkg-config --list-all", can we install qatzip into the pkg-config default directory?

**Comment by cfzhu** [comment]
hi @guoanwu, you can change the default directory when configuring QATzip lib by "./configure --prefix=/usr/",  I don't think we need to change qatzip default directory, we are using the same directory as qatlib https://github.com/intel/qatlib.git .

**Comment by guoanwu** [comment]
I see. Since the qatlib and qatzip use the pkg-config and expect to be list with "pkg-config --list-all", I think. If we install them to the pkg-config default directory, then user don't need to consider to set the "PKG_COFNIG_PATH" env. 
If we use the "--prefix=" to put it in the default directory, please have some update from the README, that will help.

**Comment by daweiq** [comment]
Close this as it's general configuration rule.
