### ISSUE TITLE
Is there a plan to support deflate_raw format for decompression

### ISSUE THREAD

**Issue by kdhanala** [intel/QATzip#84]
Under limitations from read me
_For decompression(not stream), QATZip HW only support data format including "DEFLATE_GZIP", "DEFLATE_4B", "DEFLATE_GZIP_EXT", "LZ4". Otherwise it will fallback to sw._

We use deflate_raw format for compressing and decompressing large genome file in GKL. Is there any plan to support this in future?

**Comment by cfzhu** [comment]
We have no plans to support it at the moment, we will put it into our plan.
