### ISSUE TITLE
run_perf_test.sh with VF enabled will lead qat_service restart failed for the VF devices. 

### ISSUE THREAD

**Issue by guoanwu** [intel/QATzip#86]
detail step:
1. install qat out of tree driver. [QAT out-of-tree](https://www.intel.com/content/www/us/en/download/765501/intel-quickassist-technology-driver-for-linux-hw-version-2-0.html?wapkw=QAT20)
2. install it and then the qat_service will start with PF/VF device up. 
3. run_perf_test.sh will copy the PF configure file to the /etc/4xxx_dev[#].conf. then restart the qat service will cause all the VF device configuration failed.  dmesg as:

[  464.418276] QAT: Stopping acceleration device qat_dev31.

[  464.418746] 4xxxvf 0000:e8:01.6: Resetting device qat_dev31

[  464.418747] 4xxxvf 0000:e8:01.6: Function level reset

[  464.801054] 4xxxvf 0000:e8:01.6: Starting acceleration device qat_dev31.

[  464.801935] 4xxxvf 0000:e8:01.6: HW does not support the configured services!

[  464.802229] 4xxxvf 0000:e8:01.6: Failed to start qat_dev31

[  464.802702] 4xxxvf 0000:e8:01.6: Resetting device qat_dev31

[  464.802704] 4xxxvf 0000:e8:01.6: Function level reset

One way to fix it is to recovery back the PF configuration file. （can reinstall qat out of tree driver and all the configuration file will recover back)
Not quite sure which configure cause this issue.

**Comment by XingHongChenIntel** [comment]
hello, The run_perf_test.sh script is for PF peak perf test. it's not suit for VF test.
So if you want to test the VF peak perf, may need to raise other script. please raise the request for HDL.
Then we will close this issue.
