### ISSUE TITLE
can qatzip support software accelerate like the qatenigine`s qat_sw mode

### ISSUE THREAD

**Issue by ZhaoyangJoker** [intel/QATzip#88]
When I install qatzip, I notice that it needs the root directory of the QAT driver source tree. But I hava no hardware device,so I want to know can qatzip support software accelerate like the qatenigine`s qat_sw mode？

**Comment by iaMartin8820** [comment]
qatzip需要Qat的头文件，你可以从01.org下载驱动源码，里面有头文件。然后，安装试一试。

**Comment by GarenJian-Intel** [comment]
> When I install qatzip, I notice that it needs the root directory of the QAT driver source tree. But I hava no hardware device,so I want to know can qatzip support software accelerate like the qatenigine`s qat_sw mode？

QATzip only supports hardware accelerate.

**Comment by daweiq** [comment]
Close this issue since no updated
