### ISSUE TITLE
non-standard/incomplete configure/make scripts

### ISSUE THREAD

**Issue by xwu2git** [intel/QATzip#9]
Reproduced on tags/v0.2.7.
./configure --prefix=/opt/qat --includedir=/opt/qat/include
make -j8
make install, which shows as:
install -D -m 750 /home/QATzip/src/libqatzip.a /opt/qat/lib
install -D -m 750 /home/QATzip/src/libqatzip.so /opt/qat/lib
install -D -m 750 /home/QATzip/include/qatzip.h /usr/include/
ln -s -f /opt/qat/lib/libqatzip.so /lib64/libqatzip.so
install -D -m 777 /home/QATzip/utils/qzip /opt/qat/bin

The include file is installed to /usr/incude, regardless of any prefix or includedir setting.
The lib file is installed to /lib64, regardless of any prefix setting. Just linked back to /opt/qat.
The bin/lib sub folders are not created. Instead, bin/lib files are copied and overwritten.

ls -l /opt/qat
-rwxrwxrwx 1 root root 57552 Dec 30 05:26 bin
-rwxr-x--- 1 root root 50904 Dec 30 05:26 lib

make install DESTDIR=/home/build
No effect. All other configure-based project supports the installation redirection.

**Comment by daweiq** [comment]
Thank you for point this out, we will fix this in configure issue.
