### ISSUE TITLE
QATZip + in-tree QAT driver

### ISSUE THREAD

**Issue by michaelrun** [intel/QATzip#94]
Is hugepage needed to be enabled for use in QATZip and in-tree QAT driver?

**Comment by GarenJian-Intel** [comment]
Yes.

**Comment by kkurzacz-intel** [comment]
Let me ask my question here, because it fits my use case. I have Xeon SPR 8468V and installed Ubuntu has in-tree QAT. When running `./configure`, shall I still use `--with-ICP_ROOT=$ICP_ROOT` flag and point it to driver dir? Or can I just run `./configure` without flags?

**Comment by GarenJian-Intel** [comment]
Don't use set ICP_ROOT ENV and configure this option with in-tree driver.
Please just run ./configure without flags.

**Comment by GarenJian-Intel** [comment]
Close as no more question.
