### ISSUE TITLE
Fail to use Intel QAT in QEMU VM

### ISSUE THREAD

**Issue by yingjia-wang** [intel/QATzip#95]
Hi All,

I am trying to use Intel QAT in QEMU VM, but have encountered the following errors when running QATzip.

<img width="469" alt="image" src="https://github.com/intel/QATzip/assets/43725270/2325cad6-c0f3-45a7-a4ef-4bcdaa5eb307">

I then check the dmesg message but it shows no obvious errors while building the QAT driver is also smooth.

What I have done:
(a) use vfio-pci to pass QAT in the host server to QEMU VM (both host and guest are enabled IOMMU), _lspci -nnk_ in VM shows:
<img width="835" alt="image" src="https://github.com/intel/QATzip/assets/43725270/7e31e074-c52b-464c-b170-5b10f4426920">
(b) build QAT_driver for my Intel C62x Chipset QAT, and build QATzip, _service qat_service status_ shows:
<img width="1325" alt="image" src="https://github.com/intel/QATzip/assets/43725270/8a16e89f-1945-42cd-97af-524c064aedd3">

I also try to configure QAT_driver with _--enable-icp-sriov=guest_ but the installation then fails ... :(
<img width="857" alt="image" src="https://github.com/intel/QATzip/assets/43725270/9e9f5cc7-c087-4a21-8753-f42ed2130477">

I am wondering that if I want to use QAT in VM, do I need to install QAT_driver in the host server? or simply passing it to VM is right.

Could anyone give me some hints if I have missed anything? Many thanks in advance!

**Comment by markbrown314** [comment]
Have you tried this guide [Using Intel® Virtualization Technology (Intel® VT) with Intel® QuickAssist Technology](https://cdrdv2-public.intel.com/709210/330689%20IntelQAT%20Virtualization%20AppNote%20Rev015.pdf)?

**Comment by daweiq** [comment]
Close the issue since no reply.
